Allow pilots the option to hide question marks from the OSD.
iNavFlight/inav pull request #10058
Opened 2024-05-18 19:31 UTC by MrD-RC

2024-05-19 09:19 UTC, DzikuVx requested changes

2024-05-19 09:19 UTC, DzikuVx commented on src/main/fc/settings.yaml
> +        field: highlight_djis_fuckup
Let's be professional and name this thing in a more descriptive way.. after all, this is not the first fuckup on the DJI side.
`highlight_missing_dji_chars` seems like a good idea

2024-05-22 16:23 UTC, druckgott commented
Maybe its better that people can directly. Deine the Symbol. Then they can deine? Or blank or X or what they want. And the Implementation is quite similiar

2024-05-22 18:31 UTC, MrD-RC commented
I don't see how a defined symbol is any different to showing the question mark. It would still be the same symbol in every place DJI doesn't have an appropriate symbol.

2024-05-31 09:28 UTC, DzikuVx approved these changes

2024-05-31 09:29 UTC, merged