Added Zerodrag WARP7
iNavFlight/inav pull request #10262
Opened 2024-07-30 06:38 UTC by vishnumda

* Added config.c, target.h, target.c and CMakeLists.txt

2024-08-01 14:18 UTC, mmosca commented on src/main/target/WARPF7/CMakeLists.txt
> +target_stm32f722xe(WARPF7 SKIP_RELEASES)
If you want an official target, you should remove SKIP_RELEASES here.

2024-08-02 18:22 UTC, mmosca commented on src/main/target/WARPF7/target.h
> +#define IMU_ICM42605_ALIGN          CW90_DEG
Orientation is not correct. Seems off by 180 degrees.

2024-08-02 18:23 UTC, mmosca requested changes
Please correct the board orientation and remove SKIP_RELEASES

2024-08-03 05:58 UTC, vishnumda commented on src/main/target/WARPF7/target.h
> +#define IMU_ICM42605_ALIGN          CW90_DEG
It has been changed to `CW270_DEG`.

2024-08-03 08:38 UTC, mmosca requested changes
A lot of extra files have been added. Please remove all the uneed files, from outside the target folder.

2024-08-04 13:11 UTC, mmosca commented
Adding some manual screenshots for reference.

![image](https://github.com/user-attachments/assets/336386d6-ca54-40ca-8ec4-c7a17339e0d2)

![image](https://github.com/user-attachments/assets/85fd4165-5cd8-47bf-92b9-f400c4ed9d5c)

![image](https://github.com/user-attachments/assets/2ba1bd30-0eb5-49b1-bb3b-8051548495f8)

2024-08-04 13:57 UTC, mmosca commented on src/main/target/WARPF7/target.h
> +#define USE_DSHOT
Dshot is not working, you also need #define USE_DSHOT_DMAR.

With USE_DSHOT_DMAR motor 2 is still not working. Probably need to adjust options in target.c

2024-08-04 14:37 UTC, mmosca commented
@vishnumda is this T2 pad labeled correctly?

![image](https://github.com/user-attachments/assets/d4cac80f-6172-405f-81fe-c481bbde2dad)

2024-08-04 14:42 UTC, mmosca commented
UART6 is missing in the target.

2024-08-04 14:50 UTC, mmosca commented
Board also appears to have a Camera Control pin, but it is missing the definition and the timer for that.

Is P2 supposed to be PINIO output? If so,the PINIO definitions in target.h are missing.

2024-08-04 14:52 UTC, mmosca commented on src/main/target/WARPF7/target.h
> +#define SERIAL_PORT_COUNT           6
UART6 is missing from the target.

2024-08-04 14:57 UTC, mmosca commented on src/main/target/WARPF7/target.c
> +    DEF_TIM(TIM3,   CH2,    PC7,    TIM_USE_OUTPUT_AUTO,    0, 0), // S7
Are S7 and S9 exposed on the board?

2024-08-04 15:01 UTC, mmosca commented on src/main/target/WARPF7/target.c
> +    DEF_TIM(TIM2,   CH1,    PA15,   TIM_USE_BEEPER,         0, 0),
TIM2 conflicts with S4

2024-08-04 15:01 UTC, mmosca commented on src/main/target/WARPF7/target.c
> +    DEF_TIM(TIM1,   CH2N,   PB0,    TIM_USE_OUTPUT_AUTO,    0, 0), // S1
You may want to switch the timer for S1 and S2 and it conflicts with your led timer.

2024-08-06 17:34 UTC, mmosca requested changes
Please update the target to address the pr comments

2024-12-27 06:30 UTC, vishnumda commented on src/main/target/WARPF7/target.h
> +#define SERIAL_PORT_COUNT           6
UART6 has been removed.

2024-12-27 06:33 UTC, vishnumda commented on src/main/target/WARPF7/target.c
> +    DEF_TIM(TIM3,   CH2,    PC7,    TIM_USE_OUTPUT_AUTO,    0, 0), // S7
You mean S7 and S8? Yes, they are exposed on the board with labels T6 and R6.

2024-12-27 06:33 UTC, vishnumda commented on src/main/target/WARPF7/target.c
> +    DEF_TIM(TIM2,   CH1,    PA15,   TIM_USE_BEEPER,         0, 0),
This has been fixed.

2024-12-27 06:34 UTC, vishnumda commented on src/main/target/WARPF7/target.c
> +    DEF_TIM(TIM1,   CH2N,   PB0,    TIM_USE_OUTPUT_AUTO,    0, 0), // S1
S1 timer has been changed. So it fixes the conflicts.

2025-01-12 22:18 UTC, mmosca commented
Can you merge the latest master, to make testing and validation easier?

2025-01-16 14:26 UTC, mmosca commented
The build keeps failing, probably due to the wrong number of uarts selected:

![image](https://github.com/user-attachments/assets/0de23b1c-debf-4df3-b960-30fc7aa93107)

2025-01-27 09:22 UTC, mmosca commented
Build is still failing: 
![image](https://github.com/user-attachments/assets/99bc2b09-7968-41b5-89b8-bb7345da4a50)

Can you fix the build, so we can proceed with the tests?

For the full logs, check:
https://github.com/iNavFlight/inav/actions/runs/12903988544/job/36210785483?pr=10262

2025-01-28 09:14 UTC, mmosca commented
Add ```-DWARNINGS_AS_ERRORS=ON ``` to your cmake command line, so you can build it locally with the same settings we build in github.

2025-06-18 23:07 UTC, sensei-hacker commented
Was Dshot fixed?

2025-06-19 06:04 UTC, vishnumda commented
Yes, it was fixed it is working.

2025-06-27 08:53 UTC, stronnag commented
As:
* No developer is likely to be able to do any further testing on this FC; and
* The vendor has stated that they have addressed and tested all previously raised issues.

Unless there are any objections in the next 48 hours I intend to merge this target.

2025-06-27 09:03 UTC, sensei-hacker commented
> As:
> 
> * No developer is likely to be able to do any further testing on this FC; and
> * The vendor has stated that they have addressed and tested all previously raised issues.
> 
> Unless there are any objections in the next 48 hours I intend to merge this target.


That's a coincidence. As you were writing that comment, they were writing down my address to send a board for testing.

2025-08-30 15:26 UTC, merged