enable MSP override build flag by default
iNavFlight/inav pull request #10330
Opened 2024-09-01 16:31 UTC by xznhj8129

I think this is safe to allow by default by now, a minority uses it but the chances of someone accidentally sending MSP RC commands is probably slim to none

2024-09-27 19:16 UTC, MrD-RC commented
I'm not so sure. With all the recent work with mLRS. There is potential that people will be sending MSP RC commands.

2024-09-27 19:49 UTC, xznhj8129 commented
I figured that it's an involved enough procedure that the possibility of someone sending them accidentally is pretty low, and you still need to set the override channels bitmask in CLI (ie: set msp_override_channels =  15 for 1,2,3,4) otherwise it has no effect on them

2025-01-25 01:03 UTC, sensei-hacker commented
I never understood why this was a compile flag.
If you solder an MSP device to the UART, set it up in the Ports tab, and send RC channels from it -
That's probably because you wanted to.

2025-01-25 04:16 UTC, xznhj8129 commented
> I never understood why this was a compile flag. If you buy or build a device that sends MSP RC commands, solder that MSP device to the UART, set it up in the Ports tab, and send RC channels from it - That's probably because you wanted to?

Don't forget setting up MSP Override flight mode!

2025-05-25 21:47 UTC, stronnag requested changes
I see no harm in doing this.
It requires the description in `settings.yaml` to be updated as the custom build will not longer be required.

The override mask should optimally be updated to 32bits, but that is independent and can be a separate PR.

2025-05-25 22:04 UTC, sensei-hacker commented
Also Rx.md and https://github.com/iNavFlight/inav/wiki/INAV-Remote-Management%2C-Control-and-Telemetry need to be updated to match.

2025-05-26 05:41 UTC, stronnag commented
To clear the final blocker, you need to run `src/utils/update_cli_docs.py` and commit the result. 

This will generate the settings document from CLI document from the yaml.

2025-05-26 16:05 UTC, merged