add new target - F4BY
iNavFlight/inav pull request #1159
Opened 2017-01-24 11:01 UTC by SergDoc

add new target - F4BY 
http://swift-flyer.com/
http://hobby.msdatabase.ru/project-updates/theresultsofoursurvey/f4by
http://forum.rcdesign.ru/f123/thread456525.html
http://forum.apmcopter.ru/forums/f4by/

2017-01-24 11:02 UTC, digitalentity commented
@SergDoc please note that PRs in INAV should be done to `development` branch.

2017-01-24 11:11 UTC, digitalentity requested changes

2017-01-24 11:11 UTC, digitalentity commented on src/main/target/F4BY/target.h
> +#define OSD
As far as I know F4BY doesn't have a MAX7456 board

2017-01-24 11:11 UTC, digitalentity commented on src/main/target/F4BY/target.h
> +#define USE_I2C_PULLUP
This is enabled by default in `common.h`

2017-01-24 11:11 UTC, digitalentity commented on src/main/target/F4BY/target.h
> +#define GPS_PROTO_UBLOX_NEO7PLUS
This is not safe for some Chinese GPS modules

2017-01-24 11:11 UTC, digitalentity commented on src/main/target/F4BY/target.h
> +#define CONFIG_START_FLASH_ADDRESS (0x08080000) //0x08080000 to 0x080A0000 (FLASH_Sector_8)
This is calculated automatically in INAV

2017-01-24 11:35 UTC, SergDoc commented
Ок, no problem, tomorrow...

2017-01-25 01:22 UTC, digitalentity approved these changes

2017-01-25 01:23 UTC, merged