merge cli command serialpassthrough from cleanflight
iNavFlight/inav pull request #1368
Opened 2017-03-06 14:33 UTC by metalnow

reference from cleanflight. just copy some code to implement.
I tested it and looks working. but I don't know if there are some side-effect. 
please help testing. thanks.

2017-03-06 15:18 UTC, digitalentity requested changes
This feature should only be made available for targets with enough flash - `>128K` section in `common.h`

2017-03-06 15:18 UTC, digitalentity commented on src/main/fc/cli.c
> +#ifndef SKIP_SERIAL_PASSTHROUGH
For consistency with other features this should be renamed to `USE_SERIAL_PASSTHROUGH`.

2017-03-06 15:29 UTC, metalnow commented on src/main/fc/cli.c
> +#ifndef SKIP_SERIAL_PASSTHROUGH
OK,,, Should I update all SKIP_SERIAL_PASSTHROUGH to USE_SERIAL_PASSTHROUGH? I search whole files and found one in line 499 of io/serial.c .

2017-03-06 15:31 UTC, digitalentity commented on src/main/fc/cli.c
> +#ifndef SKIP_SERIAL_PASSTHROUGH
Yes, I think we should change to `#ifdef USE_SERIAL_PASSTHROUGH` and enable that feature in `common.h` only for targets with enough flash

2017-03-06 15:40 UTC, digitalentity commented on src/main/target/CJMCU/target.h
> +#undef USE_SERIAL_PASSTHROUGH
this is not really necessary, but won't hurt

2017-03-06 15:40 UTC, digitalentity commented on src/main/target/CRAZEPONYMINI/target.h
> +#undef USE_SERIAL_PASSTHROUGH
this is not really necessary, but won't hurt

2017-03-06 15:40 UTC, digitalentity approved these changes

2017-03-06 15:41 UTC, metalnow commented on src/main/fc/cli.c
> +#ifndef SKIP_SERIAL_PASSTHROUGH
Thank you for reviewing. Hope i am doing right.

2017-03-06 15:42 UTC, metalnow commented on src/main/target/CJMCU/target.h
> +#undef USE_SERIAL_PASSTHROUGH
OK, i just leave it there.

2017-03-06 15:42 UTC, digitalentity commented
Build is still failing - now missing `#ifdef` for the feature in `cli.c`

2017-03-06 15:51 UTC, metalnow commented
Sorry, my bad. I should be more careful.

2017-03-06 17:33 UTC, oleost commented
Should CLI.md be updated to reflect this PR?

2017-03-07 08:35 UTC, metalnow commented
@oleost  it won't. I have not udpate CLI.md yet. after pr approved, I will create another pr to update CLI.md for serailpassthrough function.

2017-03-07 08:38 UTC, digitalentity commented
We need to test this in a few different use-cases, then it's ok to be merged

2017-04-09 13:41 UTC, merged