Acc notch filter
iNavFlight/inav pull request #1390
Opened 2017-03-10 21:58 UTC by DzikuVx

This might be the next thing for multirotors in INAV: Acc notch filter.

Why: I had acc problems due to big props and poor balancing: Althold poor performance and other problems. 
Acc trace before (even after I replaced bearings)
![acc no notch](https://cloud.githubusercontent.com/assets/966811/23814637/92f28e64-05e4-11e7-90aa-f948866eae1c.PNG)

After applying notch:

![acc notch](https://cloud.githubusercontent.com/assets/966811/23814642/99850fea-05e4-11e7-9fbe-4ef58eb48a7f.PNG)

Noise at 75Hz is gone! Did not enabled Angle or any GPS mode yet since it is 23:00 ATM, but gyro traces looks very very promising. I will try to continue this topic tomorrow.

But there is a problem with CPU. F3 was unable to process next notch, OLED and SoftwareSerial at the same time. Board was not booting. I'm not sure if it was memory or CPU issue. I suspect the first one.

BB log:
[blackbox_log_2017-03-10_205726 acc notch.TXT](https://github.com/iNavFlight/inav/files/835194/blackbox_log_2017-03-10_205726.acc.notch.TXT)

Work will continue to make it configurable, since it is hardcoded ATM.

2017-03-11 11:21 UTC, DzikuVx commented
Flight tested acc notch with Angle, PosHold/AltHold, RTH. Biggest progress is visible in AltHold performance. Quad altitude response was more granular, so I'm happy with the way it goes. 

[blackbox_log_2017-03-11_114959 acc notch poshold alhold.TXT](https://github.com/iNavFlight/inav/files/835694/blackbox_log_2017-03-11_114959.acc.notch.poshold.alhold.TXT)

2017-03-12 08:34 UTC, digitalentity commented
Need to test it. It might be a good option for noisy machines. It won't deminish effectiveness of proper dampening though :)

2017-07-07 21:21 UTC, DzikuVx commented
@digitalentity Once again flight tested. No negative impact on testing machine. But this is relatively noise free machine. Previous tests on 600mm quad showed some improvements in AltHold

2017-07-08 11:30 UTC, digitalentity requested changes
As long as acc notch is disabled by default - I'm ok with merging this.

2017-07-08 11:30 UTC, digitalentity commented on src/main/sensors/acceleration.c
>  PG_REGISTER_WITH_RESET_FN(accelerometerConfig_t, accelerometerConfig, PG_ACCELEROMETER_CONFIG, 0);
Please increase PG version (replace `0` with `1`) to enforce accelerometer parameter reset.

2017-07-08 13:52 UTC, merged