Update Mixer.md
iNavFlight/inav pull request #1631
Opened 2017-05-03 05:11 UTC by TNgineering

Added more details to the 'smix' procedure.

2017-05-03 09:15 UTC, digitalentity requested changes

2017-05-03 09:15 UTC, digitalentity commented on docs/Mixer.md
> +The mmix statement has the following syntax: `smix n PWM_PIN SIGNAL_SOURCE RATE SPEED	MIN	MAX`
This is not PWM_PIN, this is servo ID. The actual PWM pins are board and mixer-specific.

2017-05-03 22:56 UTC, TNgineering commented on docs/Mixer.md
> +The mmix statement has the following syntax: `smix n PWM_PIN SIGNAL_SOURCE RATE SPEED	MIN	MAX`
Ok, but does iNav still assign servos incrementally starting with the lowest?

2017-05-04 05:27 UTC, digitalentity commented on docs/Mixer.md
> +The mmix statement has the following syntax: `smix n PWM_PIN SIGNAL_SOURCE RATE SPEED	MIN	MAX`
Yes, according to what servos are used. Painless360 did quite a good video explaining how servo indexes are assinged to PWM channels here https://youtu.be/qL2LMFF5bJ4?list=PLYsWjANuAm4qdXEGFSeUhOZ10-H8YTSnH

2017-05-05 02:34 UTC, TNgineering reviewed
I changed the syntax to refer to SERVO_ID instead of PWM_PIN

2017-05-05 07:30 UTC, digitalentity approved these changes

2017-05-05 07:30 UTC, merged

2017-05-05 07:30 UTC, digitalentity commented
Thanks. Merged.