AlienFlight F7 support
iNavFlight/inav pull request #1699
Opened 2017-05-17 19:16 UTC by MJ666

don't merge, still in testing.

2017-05-20 08:25 UTC, MJ666 commented
Rebased, but not flying yet. Everything looks good at the bench, it takes of normaly but its trying to flip with any roll or pitch input. Need some more testing.

2017-05-20 10:04 UTC, sambas commented
stm32f7xx_hal_conf.h in target folder not needed anymore

2017-05-20 14:10 UTC, MJ666 commented
@sambas thanks for the heads up. Removed the file.

2017-07-08 08:10 UTC, MJ666 commented
Updated and rebased.

2017-07-08 23:18 UTC, digitalentity requested changes

2017-07-08 23:18 UTC, digitalentity commented on src/main/target/ALIENFLIGHTNGF7/target.h
> +#define USE_ADC
@MJ666 please update ADC usage to latest changes:
```
#define USE_ADC
#define ADC_CHANNEL_1_PIN               PC0
#define ADC_CHANNEL_2_PIN               PC1
#define ADC_CHANNEL_3_PIN               PC4
#define VBAT_ADC_CHANNEL                ADC_CHN_1
#define CURRENT_METER_ADC_CHANNEL       ADC_CHN_2
#define RSSI_ADC_CHANNEL                ADC_CHN_3
```

2017-07-09 08:07 UTC, MJ666 commented on src/main/target/ALIENFLIGHTNGF7/target.h
> +#define USE_ADC
Thanks for the heads up. Updated.

2017-07-09 11:00 UTC, digitalentity approved these changes

2017-07-09 11:00 UTC, digitalentity commented
@MJ666 Thanks for quick changes. I'm merging this now

2017-07-09 11:01 UTC, merged