New target KFC32F3_INAV
iNavFlight/inav pull request #1747
Opened 2017-06-01 20:28 UTC by marbalon

Just another target, F3 board with:
- MPU6000
- MS5611
- OSD
- build in RC - eLeReS - quite popular in Poland
- SPI flash
- USB - VCP
- 2x UART, 1x SPI, 10xPWM, RSSI, ADC
http://4drones.pl/files/KFC32F3_inav_top.jpg

2017-06-01 20:49 UTC, marbalon commented
If this is possible merge it before 1.7.1, changes not related with other targets.
Test failed because of NAZE flash limit...

2017-06-02 03:24 UTC, Linjieqiang commented
What SPI receiver?

2017-06-02 07:58 UTC, kabturek commented
Great stuff, looking forward to using the board with an official release!

2017-06-02 08:14 UTC, digitalentity commented
What's eLeReS receiver? Can we use the same code for REVO's RFM module to
have built-in receiver as well?

On Jun 2, 2017 10:58, "Marcin Domański" <notifications@github.com> wrote:

> Great stuff, looking forward to using the board with an official release!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/iNavFlight/inav/pull/1747#issuecomment-305717545>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AKi_m8GdXyR3XejmtzSs9nyVuVhZ3zZnks5r_8CWgaJpZM4NtgDK>
> .
>

2017-06-02 08:34 UTC, marbalon commented
Probably yes. if it is connected via SPI to main CPU. But this is compatible only with eLeReS RC - it is closed source (this receiver part is open) link quite popular in Poland.

2017-06-02 08:43 UTC, digitalentity commented
If receiver part is open, we can implement a tx part that talks the same
protocol no problem.

On Jun 2, 2017 11:34, "marbalon" <notifications@github.com> wrote:

> Probably yes. if it is connected via SPI to main CPU. But this is
> compatible only with eLeReS RC - it is closed source (this receiver part is
> open) link quite popular in Poland.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/iNavFlight/inav/pull/1747#issuecomment-305725378>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AKi_mzo6bb3njTIDwegd1Bekhc0poxMoks5r_8kogaJpZM4NtgDK>
> .
>

2017-06-02 08:44 UTC, DzikuVx approved these changes

2017-06-02 08:44 UTC, DzikuVx commented on src/main/config/parameter_group_ids.h
> +#define PG_ELERES_CONFIG 54
@marbalon clash ?

2017-06-02 08:44 UTC, DzikuVx commented on src/main/sensors/barometer.c
> +            baro.dev.calculate(&baro.baroPressure, &baro.baroTemperature);
This somehow looks like is affecting current baro implementation. I suppose it should be tested on other boards

2017-06-02 08:44 UTC, DzikuVx commented on src/main/config/parameter_group_ids.h
> +#define PG_ELERES_CONFIG 54
my bad

2017-06-02 09:12 UTC, digitalentity requested changes

2017-06-02 09:12 UTC, digitalentity commented on src/main/config/parameter_group_ids.h
> +#define PG_ELERES_CONFIG 54
Value of 54 is reserved for `PG_VTX_CONFIG`

2017-06-02 09:12 UTC, digitalentity commented on src/main/sensors/barometer.c
> +            baro.dev.calculate(&baro.baroPressure, &baro.baroTemperature);
This changes behavior of baro code. Was is tested to not break things on other boards?

2017-06-02 09:12 UTC, digitalentity commented on src/main/fc/cli.c
> +    "SUPEREXPO", "VTX", "RX_SPI", "SOFTSPI", "PWM_SERVO_DRIVER", "PWM_OUTPUT_ENABLE", "OSD", "RX_ELERES", NULL
Looks like RX_ELERES is similar to RX_SPI. I think it should be implemented using RX_SPI infrastructure - we don't need two separate implementations of SPI-based receivers.

2017-06-02 09:16 UTC, digitalentity commented
I will gladly merge KFC32F3 without eLeReS support into 1.7.1. I think we need to have eLeReS receiver support under RX_SPI infrastructure (similar to nRF24 receivers). Also, low-level hardware-related code (driving RFM module) should be moved to `drivers` directory - `rx` directory should be hardware-independent.

2017-06-02 09:25 UTC, martinbudden commented
I agree, eLeReS should be updated to use the RX_SPI framework.

2017-06-02 09:26 UTC, marbalon commented on src/main/sensors/barometer.c
> +            baro.dev.calculate(&baro.baroPressure, &baro.baroTemperature);
Yes, it was tested. just move global variable in to baro struct.

2017-06-02 09:30 UTC, marbalon commented on src/main/fc/cli.c
> +    "SUPEREXPO", "VTX", "RX_SPI", "SOFTSPI", "PWM_SERVO_DRIVER", "PWM_OUTPUT_ENABLE", "OSD", "RX_ELERES", NULL
Yes, it is stil similar to other SPI RX but require IRQ check in separate task etc. and also other configuration like telemetry, telemetry power etc. But will try to code it as regular RX_SPI receiver.

2017-06-02 09:50 UTC, martinbudden commented on src/main/fc/cli.c
> +    "SUPEREXPO", "VTX", "RX_SPI", "SOFTSPI", "PWM_SERVO_DRIVER", "PWM_OUTPUT_ENABLE", "OSD", "RX_ELERES", NULL
You don't need IRQ check in a separate task - the framework already provides for that. `rxUpdateCheck` in `rx.c` is called regularly. This in turn calls `rxRuntimeConfig.rcFrameStatusFn()` a function provided by the receiver implementation. For SPI this is `rxSpiFrameStatus` in `rx_spi.c`, which in turn calls the function pointer `protocolDataReceived` which is the thing that you should provide and set up. See `rxSpiSetProtocol` for how other protocols set this up.

2017-06-02 10:20 UTC, marbalon commented on src/main/fc/cli.c
> +    "SUPEREXPO", "VTX", "RX_SPI", "SOFTSPI", "PWM_SERVO_DRIVER", "PWM_OUTPUT_ENABLE", "OSD", "RX_ELERES", NULL
Yes, but it is called in TASK_RX, at 50Hz rate... but I found that IRQ functions for this link need to be called more often, like 500Hz.

2017-06-02 10:37 UTC, digitalentity commented on src/main/fc/cli.c
> +    "SUPEREXPO", "VTX", "RX_SPI", "SOFTSPI", "PWM_SERVO_DRIVER", "PWM_OUTPUT_ENABLE", "OSD", "RX_ELERES", NULL
`rxUpdateCheck` is not a task - it's a task check function which is called each iteration of scheduler (several kHz rate).

2017-06-02 10:37 UTC, digitalentity commented
We need to do something about NAZE target :thinking:

2017-06-02 10:40 UTC, digitalentity commented
@marbalon please remove the eleres source from this PR (you can add it later at any time).

2017-06-02 10:40 UTC, marbalon commented on src/main/fc/cli.c
> +    "SUPEREXPO", "VTX", "RX_SPI", "SOFTSPI", "PWM_SERVO_DRIVER", "PWM_OUTPUT_ENABLE", "OSD", "RX_ELERES", NULL
Ok, will try it.

2017-06-02 10:44 UTC, martinbudden commented on src/main/fc/cli.c
> +    "SUPEREXPO", "VTX", "RX_SPI", "SOFTSPI", "PWM_SERVO_DRIVER", "PWM_OUTPUT_ENABLE", "OSD", "RX_ELERES", NULL
To confirm what @digitalentity says, `rxUpdateCheck` is not called from within `TASK_RX`, it's called from the main scheduler loop. This means your `protocolDataReceived` should just check if the interrupt has occurred and return with the appropriate value. The receiver data should be processed in the `protocolSetRcDataFromPayload` function.

2017-06-02 11:48 UTC, digitalentity approved these changes

2017-06-02 12:10 UTC, martinbudden commented on src/main/target/KFC32F3_INAV/hardware_revision.c
> +void detectHardwareRevision(void)
This function is a misnomer, in that it seems to have nothing to do with detecting the hardware revision. It's also a non-standard way of setting up the GPIO pins.

2017-06-02 12:12 UTC, martinbudden requested changes
Please standardise `detectHardwareRevision `

2017-06-02 12:21 UTC, marbalon commented on src/main/target/KFC32F3_INAV/hardware_revision.c
> +void detectHardwareRevision(void)
There is no early_setup() function in inav/BF code, but sometimes if you have board with a lot of SPI devices you need to force all CS signals to high, to be sure that sensors will be detected correctly. Without this sometimes board have a problem with initialization.

2017-06-02 12:29 UTC, digitalentity commented on src/main/target/KFC32F3_INAV/hardware_revision.c
> +void detectHardwareRevision(void)
Actually there is. 
Function is called `void initialisePreBootHardware(void)` and it's controlled by `USE_HARDWARE_PREBOOT_SETUP` define. See `PIXRACER` target.

2017-06-02 12:58 UTC, martinbudden approved these changes

2017-06-02 13:38 UTC, merged

2017-06-02 13:38 UTC, digitalentity commented
@marbalon merged.

2017-06-02 13:39 UTC, digitalentity commented
Looking forward to have eLeReS support. Looks like we can also have OpenLSR support on REVO and Sparky2

2017-06-02 14:01 UTC, martinbudden commented
Yes, I also look forward to seeing eLeReS support. I think it should be fairly straightforward to fit it into the RX framework.

2017-06-02 14:14 UTC, marbalon commented
I checked RX stuff a little and hardware part can be removed and rx_spi.c from driver can be used. But I'm afraid eLeReS can't be another RX_SPI because eLeReS + RFM22 works different than NRF24 based modules.

btw.

2017-06-02 14:44 UTC, martinbudden commented
I think the best approach is for you to use the framework as much as possible, and if changes are required in the framework we can add them. The RX_SPI framework was initially developed for NRF24, but is not meant to be exclusively for NRF24. For example there is ongoing work to support  CC2500. Generally when a new class of items is added to a framework, that framework may need changes, so this is all par for the course.

What are the problems the existing framework causes for RFM22?

2017-06-02 14:50 UTC, marbalon commented
> What are the problems the existing framework causes for RFM22?
I will made a separate branch for this and will try to change eLeReS driver as much as I can to existing API and then we will talk letter... Now we can close this branch.

2017-06-03 15:49 UTC, Linjieqiang commented
@marbalon I saw your target code.You shared the SPI2 bus with MAX7456,MPU6000,RX_RFM22,FLASH.Was  it working well?