De underclock f3
iNavFlight/inav pull request #2004
Opened 2017-08-16 12:16 UTC by Schalonsus

Enabling underclock for STM32F10 targets, disabling some unused features on most F1 and enabling F1 for compiling.
Code compiled fine, but not tested yet

2017-08-17 11:20 UTC, digitalentity requested changes
Please refactor according to requested changes and test. Overall - looks good :+1:

2017-08-17 11:20 UTC, digitalentity commented on src/main/fc/cli.c
> +#if defined(STM32F1)
This can be merged to above: ` #if defined(STM32F1) || defined(STM32F3)`

2017-08-17 11:20 UTC, digitalentity commented on src/main/fc/fc_init.c
> +#ifdef STM32F1
This can be merged to above: `#if defined(STM32F1) || defined(STM32F3)`

2017-08-18 12:11 UTC, Schalonsus commented
Compiled, flashed and tested on the bench.
Will make a test flight the next days.

2017-08-18 12:18 UTC, digitalentity requested changes
Please don't enable NAZE target back. We'll merge this feature for custom firmware builders, but it's unlikely that NAZE will make it to next release. It might if we save some space, but that's not guaranteed.

2017-08-18 12:18 UTC, digitalentity commented on Makefile
> +TARGET    ?= NAZE
Please don't change back to default NAZE

2017-08-18 12:19 UTC, digitalentity commented
Cool! Let me know about outcome of the test-flight - I'm curious if it made a difference.

2017-08-22 21:48 UTC, Schalonsus commented
If i use this hex, receiver input is not working anymore

2017-08-23 05:36 UTC, digitalentity approved these changes

2017-08-23 05:36 UTC, digitalentity commented
@Schalonsus on what board?

2017-08-23 06:35 UTC, Schalonsus commented
Naze32, this even happen if i just apply the underclock code for F1/F3 to the latest master
I tested latest master 1.7.2 with underclock code and de_underclock branch 1.7.3

2017-08-23 06:36 UTC, digitalentity commented
Likely clock setup code is missing something critical. What's the output of `status` command on Naze with and without underclock option enabled?

2017-08-23 10:33 UTC, Schalonsus commented
with underclock:

CLI

# status
System Uptime: 14 seconds
Voltage: 0 * 0.1V (3S battery - OK)
CPU Clock=72MHz, GYRO=MPU6050, ACC=MPU6050.n, BARO=BMP085
Sensor status: GYRO=OK, ACC=OK, MAG=NONE, BARO=OK, RANGEFINDER=NONE, GPS=UNAVAILABLE
Stack size: 2048, Stack address: 0x20005000
I2C Errors: 0, config size: 1410, max available config: 2048
ADC channel usage:
   BATTERY : configured = ADC 2, used = none
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 1, used = none
  AIRSPEED : configured = none, used = none
System load: 5, cycle time: 2005, PID rate: 498, RX rate: 49, System rate: 9

# 


without underclock:

CLI

# status
System Uptime: 9 seconds
Voltage: 0 * 0.1V (3S battery - OK)
CPU Clock=48MHz, GYRO=MPU6050, ACC=MPU6050.n, BARO=BMP085
Sensor status: GYRO=OK, ACC=OK, MAG=NONE, BARO=OK, RANGEFINDER=NONE, GPS=NONE
Stack size: 2048, Stack address: 0x20005000
I2C Errors: 0, config size: 1410, max available config: 2048
ADC channel usage:
   BATTERY : configured = ADC 2, used = none
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 1, used = none
  AIRSPEED : configured = none, used = none
System load: 322, cycle time: 2070, PID rate: 483, RX rate: 30, System rate: 9

#

2017-08-28 12:33 UTC, merged

2017-08-28 12:33 UTC, digitalentity commented
I've merged this - will fix in that branch