Update mixer.c
iNavFlight/inav pull request #2006
Opened 2017-08-17 17:15 UTC by KenImhof

Make 3D center stick symmetrical by applying offset error, Issue #1879

2017-08-18 08:04 UTC, DzikuVx requested changes

2017-08-18 08:04 UTC, DzikuVx commented on src/main/flight/mixer.c
> +        rcCommand[THROTTLE] = rcCommand[THROTTLE] + 57; //Adjust Center Stick Accuracy, Issue #1879
There has to be a better way than hardcoded 57 here...

2017-08-18 10:32 UTC, digitalentity commented on src/main/flight/mixer.c
> +        rcCommand[THROTTLE] = rcCommand[THROTTLE] + 57; //Adjust Center Stick Accuracy, Issue #1879
I second @DzikuVx's comment. A magic number that's only valid for certain configuration is not a good way to fix things.

2017-08-18 10:40 UTC, digitalentity commented
We need to understand what parameters affect 3D mode and in what way and change that to respect possible assymetric input.

The bug here is that code calculating `rcCommand[THROTTLE]` is not aware of 3D mode.

Suggestion - change rcCommand to float. This way `rcCommand[THROTTLE]` will be in range [0;1] for normal mode and [-1;1] for 3D mode. There will be two mappings in the code - in RC input handling and in ESC output handling. Warning - this will be a massive rework.

2017-08-18 13:04 UTC, KenImhof commented
Yes, I believe the root problem is that rcCommand[THROTTLE] is not calculated as a float so the calculated value THROTTLE value is not accurate.  Since the 3D critical point is the mid-stick (1500ms) this is just a simple work-around to make the 3D THROTTLE accurate around center stick.  I agree that this does not fix the end-point errors will increase the THROTTLE error at the low point.  That is why I am proposing just applying this work-around to the 3D code.

2017-09-08 13:58 UTC, digitalentity commented
Closing, this PR is not a proper way to fix the issue.

2017-09-08 13:58 UTC, closed without merging