Add OSD_THROTTLE_POS_AUTO_THR indicator
iNavFlight/inav pull request #2217
Opened 2017-09-26 14:19 UTC by fiam

Displays stick THR position when the user controls THR directly,
actual applied THR when the navigation system controls THR.

Fixes #2031

Requires font from https://github.com/iNavFlight/inav-configurator/pull/258 and configurator updates which will be sent shortly (this message will be updated with the PR).

2017-10-03 14:19 UTC, fiam commented
@digitalentity Could you take a look at `osdFormatThrottlePosition()` and `navigationIsControllingThrottle()`? Just want to make sure I implemented them in the most straight forward way, since there are several ways to detect that THR is being controlled as well as grabbing its actual value.

2017-10-04 08:07 UTC, digitalentity requested changes

2017-10-04 08:07 UTC, digitalentity commented on src/main/navigation/navigation.c
> +    return posControl.navState != NAV_STATE_IDLE;
This is not always true. For multirotors we have 2D poshold mode which does not control throttle.

It's better to check for result of a call to `navGetCurrentStateFlags()` and also mind fixed-wing:
```
navigationFSMStateFlags_t stateFlags = navGetCurrentStateFlags();
return (stateFlags & (NAV_CTL_ALT | NAV_CTL_EMERG | NAV_CTL_LAUNCH | NAV_CTL_LAND)) || (STATE(FIXED_WING) && (stateFlags & (NAV_CTL_POS)));
```

2017-10-04 10:04 UTC, digitalentity approved these changes

2017-10-04 10:04 UTC, merged