Refactor settings, improve build times
iNavFlight/inav pull request #2239
Opened 2017-09-30 21:17 UTC by fiam

- Rename clivalue_t and associated types/functions/macros to setting_t
- Use a build stamp file to avoid running the settings generator on every make invocation

2017-10-01 07:00 UTC, martinbudden commented
This PR does two things as stated in it's description. It should be split into two. In particular I think the build stamp stuff can be merged now, but I'd like to further review the settings refactoring.

2017-10-01 07:23 UTC, digitalentity requested changes
@fiam please split thips PR into two - first one should be  makefile and generated settings optimization - I think this is what we need to have as soon as possible.

2017-10-03 14:58 UTC, fiam commented
Although there are two changes in this PR, they are related and the second one builds on top of the first one. All the commits are logically separated in self-contained units so you can look at each commit separately. The only reason I put it all in just one PR is because things have been quite slow in the past week and I didn't want to submit half of these changes, wait until they were merged and then submit the rest of them. It seemed like I was saving everyone a bit of work.

Also, the settings refactoring is only renaming (just cosmetic changes) and moving one function from cli.c to settings.c, so we can expose it to other callers. Nothing major.

2017-10-04 07:59 UTC, digitalentity approved these changes

2017-10-04 07:59 UTC, merged