clarify how nav_min_rth_distance works
iNavFlight/inav pull request #2629
Opened 2017-12-29 08:51 UTC by stronnag

Clarify the description of what update-rth-distance-description parameter actually does, to avoid having to explain it on a weekly basis to users trying to set up there modes.

2017-12-29 13:31 UTC, digitalentity requested changes

2017-12-29 13:31 UTC, digitalentity commented on docs/Cli.md
> +|  nav_min_rth_distance  | 500 | Minimum distance from homepoint when RTH full procedure will be activated [cm]. Below this distance, the mode will activate at the current location and the final phas
Typo: "iniital". Should be "initial"

2017-12-29 14:15 UTC, stronnag commented
Don't merge this, couple more typos to fix (including some new ones)

2017-12-29 14:21 UTC, stronnag commented
OK, that looks better. Ready to go I hope; sometimes you just wish you'd never started.

2017-12-30 06:12 UTC, digitalentity approved these changes

2017-12-30 07:24 UTC, merged