ADD CLRACINGF4AIRV2,fix bug for motor output for CLRACINGF4AIR
iNavFlight/inav pull request #2680
Opened 2018-01-23 18:34 UTC by bnn1044

fix the bug, Servo 3 has no output on the CLRACINGF4AIR.

Add CLRACINGF4AIR V2 To the target as the variant.

2018-01-25 07:40 UTC, digitalentity requested changes

2018-01-25 07:40 UTC, digitalentity commented on src/main/target/CLRACINGF4AIR/target.c
> +	 { TIM4,  IO_TAG(PB8),      TIM_Channel_3, 1,  IOCFG_AF_PP, GPIO_AF_TIM4,     TIM_USE_LED },                          // LED_STRIP
Indentation issue. Please use 4 spaces for indentation here (and in other places)

2018-01-30 12:33 UTC, digitalentity requested changes

2018-01-30 12:33 UTC, digitalentity commented on src/main/target/CLRACINGF4AIR/target.c
> +    { TIM12, IO_TAG(PB15),    TIM_Channel_2, 1,  IOCFG_AF_PP, GPIO_AF_TIM12,  TIM_USE_MC_MOTOR | TIM_USE_FW_SERVO },    // SERVO 5 ROLL 1
Still indentation issues. Don't use tabs.

2018-01-30 13:22 UTC, bnn1044 commented
@digitalentity  sorry for the inconvenient. corrected them now.

2018-01-30 13:41 UTC, digitalentity approved these changes

2018-02-01 01:57 UTC, merged