OSD Altitude Hold message
iNavFlight/inav pull request #3015
Opened 2018-04-07 17:45 UTC by alexeystn

I think there's no point in showing "(altitude hold)" message along with "ANGL" flight mode, when Althold + Angle modes are both activated.

Now it is a bit confusing. For example: when I fly my quad with Althold+Angle, I can see "(altitude hold)" message. When I switch on Position Hold to stop in certain point, the message disappears, even though altitude hold is still active.

Citations from iNav wiki:
> In general you shouldn't mix up ALTHOLD and ACRO/HORIZON: ALTHOLD doesn't account for extreme acro maneuvers.
> ...
> As for multicopters, iNAV is not intended to use ALTHOLD controller in anything but ANGLE mode.

Probably, we should show some warning when Althold is activated, but Angle is not.

2018-04-08 19:41 UTC, fiam requested changes
Thanks for submitting a PR! Unfortunately, it looks like we can't merge this one as it is.

The reason it's handled this way is because altitude hold in MR can be combined with other modes (it acts more like a mode modifier than a mode on its own), while position hold and 3d hold (alt+pos hold) require ANGLE mode and the FC will enable ANGLE mode even if you don't have it active.

Maybe we need to fix some documentation, but hiding these messages is definitely not the correct solution.

Please, consider joining the slack channel to discuss changes before spending time writing the code. That way we all can save a bit of time :-).

2018-04-08 20:37 UTC, alexeystn commented
Thanks! Next time I'll share my ideas in Slack beforehand :)
But one thing in iNav logic is not quite clear to me: why doesn't Althold requires Angle? When can Althold without Angle be used?

2018-04-09 12:10 UTC, fiam commented
On multirotor you can combine ALTHOLD with ANGLE or HORIZON or ACRO. On fixed wing, ALTHOLD activates ANGLE too. That's why there are 2 different paths for the messages.

2018-04-10 11:44 UTC, digitalentity commented
I agree with @fiam. This PR is not really necessary

2018-04-10 13:41 UTC, alexeystn commented
Thanks for your response!
Finally I understood the logic of this message, why and when it shows up.
But still it's a little strange to me to see "(altitude hold)" in angle moge and watch it disappearing when switching to poshold, 
even though althold is still active. I'm not persisting, just my personal opinion.

Probably, flightmode indicators like these would be the best solution: "ANG", "ANG+AH", "HOR+AH", "PH", "PH+AH", and so on. Maybe not text, but small symbols. Do you think it is worth doing?

2018-04-11 16:14 UTC, fiam commented
@alexeystn The information doesn't go away when you toggle poshold. Just poshold is one mode, while poshold+althold represents another actual flight mode (we know, it's a bit confusing, but that's what it is right now). poshold is represented by `PH` in the OSD, while PH+AH is represented by `HOLD`. Note that both of those modes imply ANGLE too, that's why they don't need any additional messages.

2018-06-24 17:28 UTC, closed without merging