Make the ROLL/PITCH/YAW PID values blink in the OSD when the corresponding RC adjustment is selected
iNavFlight/inav pull request #3252
Opened 2018-05-21 21:55 UTC by shellixyz

2018-05-22 04:20 UTC, digitalentity requested changes

2018-05-22 04:20 UTC, digitalentity commented on src/main/fc/rc_adjustments.c
> +bool isAdjustmentFunctionSelected(uint8_t adjustmentFunction) {
Calling this all the time is quite expensive. `processRcAdjustments` alredy iterates though all adjustments each RX cycle. A better way would be to keep track of active adjustment functions there and do a fast query to bitmap or array.

2018-05-22 14:20 UTC, shellixyz commented on src/main/fc/rc_adjustments.c
> +bool isAdjustmentFunctionSelected(uint8_t adjustmentFunction) {
Are you sure it is really necessary to complicate this ? The OSD is only refreshed every 16ms and `adjustmentStates` is only 4 cells big (4 maximum simultaneous adjustments). I did not profile this function but to me it the time cost should be low.

2018-06-15 19:15 UTC, digitalentity approved these changes

2018-06-18 16:04 UTC, merged