Add KISSFC target
iNavFlight/inav pull request #3822
Opened 2018-08-29 14:10 UTC by iioel

Add support of KissFC v1

2018-08-29 15:05 UTC, digitalentity requested changes
Please rebase your changes on development branch and verify the `target.h` definitions

2018-08-29 15:05 UTC, digitalentity commented on src/main/target/KISSFC/target.h
> +#define USABLE_TIMER_CHANNEL_COUNT 11
This is not needed for INAV

2018-08-29 15:05 UTC, digitalentity commented on src/main/target/KISSFC/target.h
> +#define USED_TIMERS             (TIM_N(1) | TIM_N(2) | TIM_N(3) | TIM_N(4) | TIM_N(8) | TIM_N(15) | TIM_N(16) | TIM_N(17))
This is not needed

2018-08-29 19:42 UTC, iioel commented
Useless lines removed and I have rebased my branch. Is it ok ?

2018-08-31 09:45 UTC, iioel commented
Timers reviewed.
Just need to test on the board.

2018-09-01 19:42 UTC, digitalentity approved these changes

2018-09-03 22:52 UTC, iioel commented
Motors and servo output are working now (tested on the board), reciver with crsf too

2018-09-04 17:19 UTC, merged