Add target SPRACINGF7DUAL
iNavFlight/inav pull request #3900
Opened 2018-10-03 16:38 UTC by 0xQSL

This pull request imports the SPRACINGF7DUAL from Betaflight and gets it to build. I've separated importing and fixing into different commits for better accountability.

This currently does not work for me: After flashing my board doesn't get a serial connection in the configurator. I'll propably get a debugger at some point to see what is happening. The board works fine with Cleanflight.

I'd appreciate any pointers as to where to start looking for mistakes as I'm new to inav(and cf/bf).

Ping @hydra: consider removing inav from your description until this works

2018-10-03 17:42 UTC, hydra commented
Hiya, there are some things to note regarding the SPRacingF7DUAL.

1) It has two gyros, both gyro SPI cable select pins MUST be initialized and set to inactive before attempting to use either of the gyros. Certainly you want to check the hardware initialisation of the gyro pins as the first thing to do otherwise it will NOT be reliable to a) fly, b) initialise consistently - especially on cold boots.  See the CF/BF gyro dual initialisation code for reference.
2) UART5 RX is physically shared with the BIND button pin.  Ensure there is no conflict between button and uart code.
3) Motor outputs 4-5 are used to control the FX758-2-SPI VTX, when not using the VTX they are free for motor outputs, ensure any motor and vtx code is not conflicting.


I've never worked on the iNav codebase and don't currently have a lot of time free due to other commitments but if you get totally stuck let me know and perhaps I can help out.

2018-10-03 18:47 UTC, digitalentity commented
@hydra Thanks for chiming in!

INAV's busDevice code initializes all defined CS# pins to logic "1" on boot, no problem with that. I'll consider the rest when reviewing this 😄

2018-10-03 18:51 UTC, hydra commented
@digitalentity no worries!  Happy to help but I'm very time poor.  I corrected my previous comment, should have read motor outputs 5-8, not 4-5.

2018-10-03 18:53 UTC, digitalentity commented
@hydra pretty much same here - time is a scarce resource. Cheers 🍻

2018-10-05 17:08 UTC, 0xQSL commented
Thank you both for replying so fast 👍 
I've added a commit to get both gyros cs pins initialized and use one of them. I've now got a working configurator  :raised_hands:
Getting a working debugger with openocd took some time but was very helpful.

I'll look further at gyro initialization and points 2/3. I'll also look through all defines in target.h to see which are actually used.

2018-10-05 18:01 UTC, hydra commented
Great work.

I think also you might need to enable internal pullup for the gpio input for the sd card detect, i have a feeling i designed it without an external pull-up resistor.

2018-11-14 23:54 UTC, hydra commented
@0xQSL Did you progress this any further?

Also, with regard to my previous comment regarding SD Card detect. I was wrong, there is no SD Card detect wired up to the MCU on the SP Racing F7 DUAL.  You just attempt to read the card at bootup and use it if it works.

2018-11-15 21:00 UTC, 0xQSL commented
I've been using this on my hex with:

- 6x motor
- gps, compass (m8n)
- uarts for sbus and telemetry
- another uart for rf-module
- led strip
- sd-card (I'd checked your cleanflight code didn't see any cd-pin, so i just tried it and it worked)

I can't check vtx as i've got one of the stacking boards but need motors 5 and 6.
Alignment may also be wrong I just rotated it to match. Anything else works.

2018-11-15 21:18 UTC, hydra commented
@digitalentity can we get this merged? We can add other hardware support on an as-needed basis.

The SPRacingF7DUAL is quite suited to iNAV due to its 8 motor output support, GPS connectors, on-board baro, extensive IO support and very capable CPU.

2018-11-15 21:27 UTC, digitalentity requested changes
Please address comments and rebase as this branch is no longer up to date with `development`. After that this could be merged.

2018-11-15 21:27 UTC, digitalentity commented on src/main/target/SPRACINGF7DUAL/target.h
> +#define USABLE_TIMER_CHANNEL_COUNT 16
This is no longer needed

2018-11-15 21:27 UTC, digitalentity commented on src/main/target/SPRACINGF7DUAL/target.h
> +#define SDCARD_DMA_TX                       DMA1
SDCARD definitions need refactoring. A lof of defines is not needed:

```
#define SPI3_CLOCK_LEADING_EDGE

#define USE_SDCARD
#define USE_SDCARD_SPI
#define SDCARD_SPI_BUS          BUS_SPI3
#define SDCARD_CS_PIN           PC3
```

2018-11-15 21:27 UTC, digitalentity commented on src/main/target/SPRACINGF7DUAL/target.h
> +#define USE_MAG_HMC5883
Please add mode supported compasses, at least QMC5883

2018-11-15 21:27 UTC, digitalentity commented on src/main/target/SPRACINGF7DUAL/target.c
> +BUSDEV_REGISTER_SPI(busdev_mpu6500_2,     DEVHW_MPU6500,      MPU6500_2_SPI_BUS,    MPU6500_2_CS_PIN,     GYRO_2_EXTI_PIN,  DEVFLAGS_NONE);
It's better to decrare both gyros here and add `USE_TARGET_IMU_HARDWARE_DESCRIPTORS` definition to `target.h`

2018-11-16 21:56 UTC, hydra commented
@digitalentity thanks for review.   @0xQSL do you have time to make the requested changes and update the PR?

2018-11-17 21:16 UTC, 0xQSL commented
Yes, I'll do it some time next week

2018-11-28 10:05 UTC, 0xQSL commented
I've updated this pull request.
All sensors still read and motors still spin but i haven't flown with it yet.

2018-11-28 15:14 UTC, hydra commented
@0xQSL Thanks for the update, any idea when will you get a change to test-fly it?

2018-11-28 18:27 UTC, digitalentity approved these changes

2018-11-29 09:59 UTC, 0xQSL commented
> @0xQSL Thanks for the update, any idea when will you get a change to test-fly it?

I just did a quick test flight, everything works fine

2018-11-29 11:18 UTC, hydra commented
@0xQSL Great!
@DigialEntity ready to merge now?

2018-11-29 19:30 UTC, merged

2018-11-29 19:30 UTC, digitalentity commented
@0xQSL @hydra merged, thanks!

2018-11-29 20:42 UTC, hydra commented
@digitalentity Great, thank you both too.