Logic Conditions framework
iNavFlight/inav pull request #4144
Opened 2019-01-02 19:26 UTC by DzikuVx

2019-01-02 23:10 UTC, rb1205 commented
Is this intended for convertiplanes / VTOL flight?

2019-01-03 07:46 UTC, DzikuVx commented
@rb1205 VTOL is only one reason for it. This will solve the problem of swapped control axises after conversion from vertical to horizontal flight, but only this one

2019-01-04 08:35 UTC, hali9 commented
Do you plan to do the same for mmix?
It would be necessary to do it for mmix for VTOL.

2019-01-04 08:47 UTC, DzikuVx commented
@hali9 yes

2019-03-05 14:35 UTC, shellixyz commented on src/main/fc/cli.c
> +    int args[10], check = 0;
Why 10 ? Looks like 6 would be enough.

2019-03-05 14:40 UTC, shellixyz commented on src/main/fc/cli.c
> +    int args[10], check = 0;
Why 10 ? Looks like 8 would be enough

2019-03-05 14:43 UTC, shellixyz commented on src/main/fc/cli.c
> +            cliLogic("");
Is that intended or you put this only for debugging ?

2019-03-05 14:46 UTC, shellixyz commented on src/main/fc/cli.c
> +        //TODO implement
Leftover ?

2019-03-05 14:52 UTC, shellixyz commented on src/main/fc/fc_msp.c
> +        if ((dataSize == 12) && (tmp_u8 < MAX_SERVO_RULES)) {
12 ? You're reading only 6

2019-03-05 14:52 UTC, shellixyz commented on src/main/fc/fc_msp.c
> +            customServoMixersMutable(tmp_u8)->rate = sbufReadU8(src);
Rate should be int16 now

2019-03-05 19:33 UTC, shellixyz requested changes
Otherwise LGTM

2019-03-05 19:33 UTC, shellixyz commented on src/main/fc/fc_msp.c
> +            sbufWriteU8(dst, customServoMixers(i)->rate);
Please replace `sbufWriteU8` with `sbufWriteU16`. The servo mixer rate is now int16

2019-03-05 19:37 UTC, shellixyz approved these changes

2019-03-05 21:31 UTC, merged

2019-03-06 12:31 UTC, stronnag commented
small fyi,
```
%% logic_condition.c 
./src/main/common/logic_condition.c: In function 'logicConditionUpdateTask':
./src/main/common/logic_condition.c:237:40: warning: unused parameter 'currentTimeUs' [-Wunused-parameter]
 void logicConditionUpdateTask(timeUs_t currentTimeUs) {
                               ~~~~~~~~~^~~~~~~~~~~~~
```

2019-03-18 15:43 UTC, stronnag commented
I currently (505f44ad8) have to set
```
logic 0 1 0 0 0 0 0 0
```
(whatever that does :) to have working servos. Is this expected ? 
Shouldn't the default be "work as legacy".

2019-03-19 07:45 UTC, DzikuVx commented
yes, `-1` with `smix`. I will check defaults tho

2019-03-19 08:26 UTC, stronnag commented
On March 19, 2019 7:45:04 AM UTC, "Paweł Spychalski" <notifications@github.com> wrote:
>yes, `-1` with `smix`. I will check defaults tho
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/iNavFlight/inav/pull/4144#issuecomment-474231953

Thanks. As I'd just restored a 0,0 diff, user error not checking what had changed. Probably saved me from flying a light, floaty wing in far too much wind.