Fix FIR init
iNavFlight/inav pull request #4538
Opened 2019-03-24 17:13 UTC by DzikuVx

FIR has to be inited and buffer initialized in case user changes FIR from OFF to ON. Other option is to have dummy function pointers or listeners in MSP and CLI to init it before PID loop is executed. Let's assume this is fine for now

2019-03-24 17:46 UTC, digitalentity requested changes

2019-03-24 17:46 UTC, digitalentity commented on src/main/flight/pid.c
This should be per axis

2019-03-24 20:00 UTC, digitalentity approved these changes

2019-03-24 20:00 UTC, digitalentity commented on src/main/flight/pid.c
>          firFilterInit(&pidState[axis].gyroRateFilter, pidState[axis].gyroRateBuf, PID_GYRO_RATE_BUF_LENGTH, dtermCoeffs);
In case of `!use_dterm_fir_filter` we can use length of 2 instead of `PID_GYRO_RATE_BUF_LENGTH`

2019-03-27 08:00 UTC, DzikuVx commented
OK, I'm merging as it is. Those 3 floats could be saved but overhead of managing buffer length at runtime in CLI and MSP seems like an overkill

2019-03-27 08:00 UTC, merged