OSD Hud + LoRa radar (nearby aricrafts)
iNavFlight/inav pull request #4558
Opened 2019-03-28 14:45 UTC by OlivierC-FR

As a subset of the crosshair, adds the ability for the OSD to display points of interest (POI) in "3D".
Also adds the support to display the nearby aircrafts from the project "iNav radar", using a 433/868/915MHz ESP32 modem , see here : https://github.com/mistyk/inavradar-ESP32

Samples : 
https://drive.google.com/file/d/1fiEglzfM1DVzJaWzt7Yn5e-RmmaHZMy0/view (some  visuals are outdated)
Pursuit : https://www.youtube.com/watch?v=7ww0YOGN7F0

![000](https://user-images.githubusercontent.com/25566932/55166582-ae5c1200-516f-11e9-8a0c-16f262846e85.jpg)

![002](https://user-images.githubusercontent.com/25566932/55166598-b5832000-516f-11e9-916a-0182b0a099c4.jpg)

![003](https://user-images.githubusercontent.com/25566932/55166611-bae06a80-516f-11e9-85c9-d030cde5fce4.jpg)

![004](https://user-images.githubusercontent.com/25566932/55166618-be73f180-516f-11e9-9d64-b98e1a257e7c.jpg)

![001](https://user-images.githubusercontent.com/25566932/55166633-c2077880-516f-11e9-9871-6a77e65781df.jpg)

2019-03-28 14:50 UTC, DusKing1 commented
Awesome! You're faster than I thought!

2019-03-28 15:05 UTC, DzikuVx commented
@fiam you might want to take a look
@OlivierC-FR hmm... a lot of conflicts ;)

2019-03-28 15:09 UTC, OlivierC-FR commented
**How to install :**

### **1 : Configure the Hud**

- Flash the build for your target, dump back the full config
- REQUIRE a compatible OSD font from this set : http://bit.ly/2RJ0QnW
- Go in the CMS menu (OSD menu), section : OSD > HUD
- Set the camera uptilt for the FPV camera, by default zero. That's the angle in degres between the horizontal of the aircraft and the line of sight of the camera. For a quad it's a positive value, usually between 5 and 30°. For a  plane it's often a negative value, from 0 to -10°
- The FOV (field of view) for the camera can be adjusted, the default values are about ok for a 2.8mm lens. If your camera is a 2.5 or 2.1, try to raise both the horizontal and vertial FOVs by 5 or 10°. If the FOV is wrong, the tracking won't work too well near the borders of the screen.

### **2 : To display nearby aircrafts from your ESP32 modem**

Please see how to install the modem there : https://github.com/mistyk/inavradar-ESP32
- In the CMS, OSD > Hud, Set "Display mode to 3D or Map.
3D is recommended, for now Map mode only shows 1 POI, while 3D mode can display up to 8 (counting the home and waypoints)
- In OSD > Hud > More Settings, you can choose if you want to see the home point or not, and how many nearby aircraft you want to see, aswell the max and minimum distances.
- Margin horizontal and vertical are setting how far from the border of the screen the hud must stop.

### **3 : To display the homing crosshair**

- In OSD > HUD > Homing = ON
- There you can also set the focus for the homing, narrow, medium or wide. Default is medium.

### **4 : More **

- All there features obviously require a GPS, and some will require the home lock.
- The homing crosshair is independant from the 3D and map displays. Although, it requires the camera uptilt to be set.
- There's an extra setting added by this PR, in OSD > Settings > Horizon offset, to move the whole Hud and crosshair from -2 to +2 line, vertically.
- And 7 different crosshairs to chosse from, see  OSD > Settings > Crosshair style

### **5 : CLI commands ** 

All the settings are available from the CLI, defaults are :

`set osd_crosshairs_style = DEFAULT
set osd_horizon_offset = 0

set osd_homing = 0
set osd_homing_focus = MEDIUM

set osd_camera_uptilt = 0
set osd_camera_fov_h = 135
set osd_camera_fov_v = 85

set osd_hudmode = 3D
set osd_hud_margin_h = 6
set osd_hud_margin_v = 3
set osd_hud_disp_home = 1
set osd_hud_disp_radar = 4
set osd_hud_disp_wp = 0
set osd_hud_disp_mindist = 1
set osd_hud_disp_maxdist = 4000
set osd_hud_debug = 0`

2019-03-28 15:21 UTC, OlivierC-FR commented
Will fix the conflicts later, it's not something I can do in 5 minutes, I didn't notice there was some many change on the OSD side while I was still working on a 2.1 base

2019-03-28 15:32 UTC, wx4cb commented
nice... i miss my homing crosshair :D

2019-03-28 16:22 UTC, OlivierC-FR commented
Closing, with redo over a fresh 2.2 dev

2019-04-04 11:32 UTC, OlivierC-FR commented
Reworked the menus, added a setting to adjust the radar cycle time (for the link quality display), and a less intrusive way to display the debug infos about the nearest radar POI.

![0404-1](https://user-images.githubusercontent.com/25566932/55552562-fa620600-56dd-11e9-9a4e-a197b730883b.jpg)
![0404-2](https://user-images.githubusercontent.com/25566932/55552563-fa620600-56dd-11e9-85c6-e63eb8ba28c1.jpg)
![0404-3](https://user-images.githubusercontent.com/25566932/55552564-fa620600-56dd-11e9-8c19-148c90e83db2.jpg)

2019-04-10 07:11 UTC, Pairan commented
@OlivierC-FR ... doest it have to be the modules with display or will the ones without do as well? We will go for it ;)

2019-04-10 07:59 UTC, OlivierC-FR commented
> 
> 
> @OlivierC-FR ... doest it have to be the modules with display or will the ones without do as well? We will go for it ;)

As long as it has an ESP32 it should work I guess, but to be sure, I'm using the 433MHz that is listed there : https://github.com/mistyk/inavradar-ESP32
Over the 4 I have, 3 have broken OLEDs (2 broken on arrival, 1 felt off the bench, very fragile), and they still work fine.
But the good thing with the OLED is that you can check ho many peers they connect to.

2019-04-10 08:22 UTC, Pairan commented
Perhaps this should be included more into the iNav system to get even better: 
- instead of the username it could by default use the name of the Vessel
- some setting in an extra page to get rid of the display on the module like params and stuff

but overall this is what I've been looking for.

We will plan to go for 868MHz ... this will get exciting. Thanks for you reply, mon ami!

2019-04-10 11:52 UTC, OlivierC-FR commented
It is already using the name that is set for the aircraft in inav, see as sample on this photo, it displays "DARTXL" for my plane.
If there's no name set, it get assigned a random string of 5 chars.

Just a word of warning, I'm not sure the 868MHz version was ever tested, I think all the testers we have so far are with 433MHz. It should work but.... just in case, that's all very early stages in the developement process, normal operation is not guaranted ;)

![20190410_113142](https://user-images.githubusercontent.com/25566932/55876312-a3ee3f00-5b97-11e9-9ff1-3c8b5c627f71.jpg)

2019-04-10 12:27 UTC, Pairan commented
nice .. and thanks for the warning/hint about 868MHz ... as we're not on the run, we'll take the time it needs to get there ... And V2.2 is far from being released so ... no worries ;)

2019-04-11 10:04 UTC, ZinhoRacing commented
Just to say that I tested with 2 units on  868Mhz without issue.... on the  bench. :smilley:

2019-05-08 11:46 UTC, DzikuVx requested changes

2019-05-08 11:46 UTC, DzikuVx commented on src/main/io/osd.c
>  PG_REGISTER_WITH_RESET_FN(osdConfig_t, osdConfig, PG_OSD_CONFIG, 7);
@OlivierC-FR you have to bump PG version to avoid clashes during migration without full chip erase

2019-05-08 11:46 UTC, DzikuVx commented on src/main/io/osd.c
> +
I know, I'm just just making this stupid comment about empty lines

2019-05-08 11:46 UTC, DzikuVx commented on src/main/io/osd_hud.c
> + * This file is part of Cleanflight.
Let's change it to INAV

2019-05-08 11:46 UTC, DzikuVx commented on src/main/msp/msp_protocol.h
> +#define MSP_SET_RADAR_POS        248 //SET radar position information
I would prefer to have it in MSP2 range but OK, probably it's more probable to get 3rd party support if MSPv1 is used since there are libs that work with MSPv1

2019-05-08 12:12 UTC, OlivierC-FR commented on src/main/msp/msp_protocol.h
> +#define MSP_SET_RADAR_POS        248 //SET radar position information
Yes I think MSP1 will make it compatible with a lot more other projects

2019-05-08 12:13 UTC, OlivierC-FR commented on src/main/io/osd.c
>  PG_REGISTER_WITH_RESET_FN(osdConfig_t, osdConfig, PG_OSD_CONFIG, 7);
done

2019-05-08 12:13 UTC, OlivierC-FR commented on src/main/io/osd.c
> +
done

2019-05-08 12:13 UTC, OlivierC-FR commented on src/main/io/osd_hud.c
> + * This file is part of Cleanflight.
done

2019-05-08 13:08 UTC, DzikuVx approved these changes

2019-05-15 19:20 UTC, OlivierC-FR commented
This PR must not be merged as-is, since the last commits (additions of MSP2 and next) I getting critical reliability issues on my 5" quad, been working on it for several days now, havn't yet managed to pinpoint the cause. Need more time.

2019-05-16 13:05 UTC, OlivierC-FR commented
Looks like it's fixed now, also made few tweaks on the ESP32 side that could only make it better.
It's possible the unstability is from the Matek F405 board itself, next flights will tell more.

2019-05-24 13:37 UTC, merged