Remove sticks arming
iNavFlight/inav pull request #4640
Opened 2019-04-24 12:28 UTC by DzikuVx

closes #4583

2019-04-24 18:55 UTC, DzikuVx commented
ok, looks like I have to fix conflicts :)

2019-04-24 18:56 UTC, digitalentity requested changes

2019-04-24 18:56 UTC, digitalentity commented on src/main/fc/rc_modes.c
> -    return isUsingSticksToArm;
@DzikuVx you missed the declaration of `isUsingSticksToArm` and other places where it's referenced.

2019-04-24 19:14 UTC, DzikuVx commented
@digitalentity rebased and fixed

2019-04-24 19:22 UTC, digitalentity approved these changes
LGTM

2019-04-24 22:14 UTC, merged

2019-05-04 18:47 UTC, hali9 commented
If I good undestand code this PR also removed fixed_wing_auto_arm
This is probably not intentional.

2020-03-29 20:37 UTC, mikegeeezy commented
So did this happen?  Because I can't arm with sticks anymore.  And I can't find the setting to prevent disarm unless the throttle is idle.