Change VTX power level via switch
iNavFlight/inav pull request #4717
Opened 2019-05-17 17:34 UTC by L4ky

Hi, 
this PR allow user to change VTX power during the flight.
I used "Adjustments" mechanism to avoid huge modification to iNav's code.

I'm not sure in "rc_adjustments.c" if it's correct to use "VTX_SETTINGS_MIN_POWER" and "VTX_SETTINGS_MAX_POWER" to constrain the variable which sets the power level.

My advice is to use a 3-pos switch or a potentiometer and set the same channel in "Range Channel" and "Adjustment Channel".

I tested it only on my Eachine Smartaudio VTX.

Note: i have PR ready for inav-configurator to add this feature. I'll wait for this to get accepted before proposing that.

2019-05-21 10:35 UTC, L4ky commented
While i wait for approval or changes, iNav Configurator PR: [#775](https://github.com/iNavFlight/inav-configurator/pull/775)

2019-05-21 13:47 UTC, shellixyz requested changes
Please rebase your branch upon the development branch and fix the indentation. We are using 4 spaces per level and no tabs.

Otherwise looking good to me

2019-05-21 14:29 UTC, L4ky commented
After some mess i should have rebased correctly.

2019-05-21 14:52 UTC, shellixyz approved these changes
Since you originally based your branch upon master it picked up 3747ca451 but it is not a big deal. LGTM

2019-05-23 14:04 UTC, merged

2019-10-02 19:43 UTC, whoim2 commented
This working now? (Change vtx power via swith)