Graupner Targets
iNavFlight/inav pull request #4884
Opened 2019-06-26 19:28 UTC by Scavanger

On special request from @Ralfde and Graupner:

Allow up to 12 servos for bigger airplanes: 
new targets: 
GRAUPNERF413: 1 motor, 12 servos, UARTs: 1, 3 shared with I2C, 6, softserial 
GRAUPNERF4V6: 2 motors, 8 servos 
GRAUPNERF4V3: 1 motor at PPM pin, 6 servos 
GRAUPNERF7NXT: 2 motors, 8 servos

2019-06-26 20:40 UTC, DzikuVx commented
@Scavanger please read https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md

2019-06-26 20:46 UTC, DzikuVx requested changes

2019-06-26 20:46 UTC, DzikuVx commented on src/main/drivers/pwm_mapping.h
> +#define MAX_PWM_SERVOS 12
There already is #4868 that changes that

2019-06-26 20:46 UTC, DzikuVx commented on src/main/target/FIREWORKSV2/target.c
> +//	DEF_TIM(TIM3, CH1, PC6,                    TIM_USE_FW_SERVO,    0, 0),	// S14 TX6
used or not?

2019-06-26 20:46 UTC, DzikuVx commented on src/main/target/FIREWORKSV2/target.c
> +//	src/main/drivers/pwm_mapping.h line 26-34
Not needed comment

2019-06-26 20:46 UTC, DzikuVx commented on src/main/target/OMNIBUSF4/target.c
> +//    DEF_TIM(TIM10, CH1, PB8,  TIM_USE_MC_SERVO | TIM_USE_FW_MOTOR, 0, 0), // PPM
Why those are commented out?

2019-06-26 20:46 UTC, DzikuVx commented on src/main/target/OMNIBUSF4/target.c
> +//    DEF_TIM(TIM4,  CH3, PB8,  TIM_USE_MC_SERVO | TIM_USE_FW_MOTOR, 0, 0), // PPM	TIM4_CH3	TIM10_CH1
Please remove

2019-06-26 20:46 UTC, DzikuVx commented on src/main/target/OMNIBUSF7NXT/target.c
> +//    DEF_TIM(TIM3, CH3, PB0, TIM_USE_MC_MOTOR | TIM_USE_FW_SERVO,    1, 0),  // D(1, 7, 5)
Please remove unused and commented timer definitions is this file too

2019-06-26 20:55 UTC, digitalentity commented
Those targets need some serious cleanup before they could be considered. Now they have a lot of unneeded artifacts and are quite a pain to maintain.

2019-06-27 05:03 UTC, Ralfde commented
All Graupner targets use Omnibus hardware, just software is changed for Graupner airplane customers:
GRAUPNERF413: Omnibus F4V6 (second accel/gyro will be added
GRAUPNERF4V6 = Omnibus F4V6
GRAUPNERF4V3 = Omnibus F4V3
GRAUPNERF7NXT = Omnibus F7NXT
Our airplane customers need more servos for the airplanes and this is why I made new targets.
In case we should offer just custom builds to our customers, we could do so, except of the GRAUPNERF413, which should get a new layout, soon, so the user can better use it for airplanes.

Not needed command lines could be deleted.

2019-06-27 05:47 UTC, Ralfde commented
The cleaned code:
[scr.zip](https://github.com/iNavFlight/inav/files/3333092/scr.zip)

2019-07-16 18:05 UTC, Ralfde commented
[servos.zip](https://github.com/iNavFlight/inav/files/3398473/servos.zip)
I think this should solve the conflict.

2019-07-16 19:18 UTC, Ralfde commented
[servos.zip](https://github.com/iNavFlight/inav/files/3398473/servos.zip)
I think this should solve the conflict.

2019-09-15 07:18 UTC, digitalentity commented
Sorry, this fell through the cracks. @Ralfde is this still relevant?

2019-09-15 07:18 UTC, digitalentity commented
@Scavanger can you amend the PR?

2019-09-15 08:57 UTC, Ralfde commented
Found some wrong definitions in the GRAUPNERF413 target for the I2C.
Please use the new file for the FIREWORKSV2 TARGET:
[target.zip](https://github.com/iNavFlight/inav/files/3613554/target.zip)

As all other changes seem to be already in the development tree, except the new targets, I think it's maybe better to split the Graupner targets in seperate target folders to have it seperated and a better overview in the code. If you would prefer this, too, please use this new targets instead of the changes in the other targets:
I compiled them already with the latest development code and no error occured.
[target.zip](https://github.com/iNavFlight/inav/files/3613563/target.zip)

2019-11-28 10:23 UTC, closed without merging