Add SPL006-001 barometer driver
iNavFlight/inav pull request #5028
Opened 2019-08-20 16:49 UTC by shellixyz

The SPL006-001 is a precise barometer pin-to-pin compatible with the BMP280

2019-08-20 18:43 UTC, digitalentity requested changes

2019-08-20 18:43 UTC, digitalentity commented on src/main/target/common_hardware.c
> +      BUSDEV_REGISTER_SPI(busdev_bmp280,      DEVHW_SPL006,       SPL006_SPI_BUS,     SPL006_CS_PIN,      NONE,           DEVFLAGS_NONE);
Replace `busdev_bmp280` with `busdev_spl006`

2019-08-20 18:43 UTC, digitalentity commented on src/main/sensors/barometer.h
> +    BARO_MAX = BARO_SPL006
Let's keep the `FAKE` baro the last one

2019-08-20 18:43 UTC, digitalentity commented on src/main/drivers/barometer/barometer_spl006.c
> +nack_error:
Generally `goto` should be avoided if possible. Here instead of `goto` you can just `return false`

2019-08-20 18:43 UTC, digitalentity commented on src/main/drivers/barometer/barometer_spl006.c
> +        if (ack && chipId == SPL006_DEFAULT_CHIP_ID) return true;
Coding style: 
```
if (condition) {
    return true;
}
```

2019-08-20 18:43 UTC, digitalentity commented on src/main/drivers/barometer/barometer_spl006.c
> +    if (pressure) *pressure = lrintf(spl006_compensate_pressure(spl006_pressure_raw, spl006_temperature_raw));
Coding style: 
```
if (condition) {
    return true;
}
```

2019-08-20 18:43 UTC, digitalentity commented on src/main/drivers/barometer/barometer_spl006.c
> +    if (temperature) *temperature = lrintf(spl006_compensate_temperature(spl006_temperature_raw) * 100);
Coding style: 
```
if (condition) {
    return true;
}
```

2019-08-20 18:43 UTC, digitalentity commented
Mainly being picky about the style :smile:

2019-08-20 22:08 UTC, shellixyz commented
@digitalentity Should be good to go now

2019-08-21 10:53 UTC, digitalentity approved these changes
LGTM!

2019-08-25 00:14 UTC, merged