fixed craft name spaces bug
iNavFlight/inav pull request #5348
Opened 2020-01-25 19:49 UTC by uotw

Fixed bug where the craft name seems to ignore every other character on DJI Goggles.

Bug verified [here](https://www.rcgroups.com/forums/showthread.php?3371977-DJI-Digital-FPV-System-Owners/page246).

2020-01-27 08:57 UTC, DzikuVx commented
@digitalentity

2020-01-29 16:45 UTC, digitalentity requested changes

2020-01-29 16:45 UTC, digitalentity commented on src/main/io/osd_dji_hd.c
> +	   break;
Fix alignment here please

2020-01-29 16:55 UTC, uotw commented
Fixed.

******************************************
Ben C. Smith, MD, FACEP
Associate Professor
Director of Emergency Ultrasound
The University of Tennessee
Department of Emergency Medicine
@UltrasoundJelly
UltrasoundoftheWeek
******************************************


On Wed, Jan 29, 2020 at 11:45 AM Konstantin Sharlaimov <
notifications@github.com> wrote:

> *@digitalentity* requested changes on this pull request.
> ------------------------------
>
> In src/main/io/osd_dji_hd.c
> <https://github.com/iNavFlight/inav/pull/5348#discussion_r372500707>:
>
> > @@ -397,10 +397,13 @@ static mspResult_e djiProcessMspCommand(mspPacket_t *cmd, mspPacket_t *reply, ms
>              break;
>
>          case DJI_MSP_NAME:
> -            for (const char * name = systemConfig()->name; *name; name++) {
> -                sbufWriteU8(dst, *name++);
> -            }
> -            break;
> +            {
> +                const char * name = systemConfig()->name;
> +                int len = strlen(name);
> +                if (len > 12) len = 12;
> +                sbufWriteData(dst, name, len);
> +           }
> +	   break;
>
> Fix alignment here please
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/iNavFlight/inav/pull/5348?email_source=notifications&email_token=ADLUWJZRDHKFWSKBGDP27YLRAGXCTA5CNFSM4KLSULCKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCTQIPHI#pullrequestreview-350259101>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADLUWJYXAWBUIEOSTCHC5RLRAGXCTANCNFSM4KLSULCA>
> .
>

2020-01-29 20:21 UTC, merged

2020-01-29 20:23 UTC, digitalentity commented
Actually not fixed (INAV uses spaces instead of tabs), but I've taken care of that :smile: 
Thanks

2020-01-29 21:26 UTC, uotw commented
Ah!  Thanks Konstantin.  I hope to contribute however I can with this
project, but I'm primarily a javascript developer.  C takes me back to
college...

******************************************
Ben C. Smith, MD, FACEP
Associate Professor
Director of Emergency Ultrasound
The University of Tennessee
Department of Emergency Medicine
@UltrasoundJelly
UltrasoundoftheWeek
******************************************


On Wed, Jan 29, 2020 at 3:23 PM Konstantin Sharlaimov <
notifications@github.com> wrote:

> Actually not fixed (INAV uses spaces instead of tabs), but I've taken care
> of that 😄
> Thanks
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/iNavFlight/inav/pull/5348?email_source=notifications&email_token=ADLUWJ6TUEOUX3767EXNCZLRAHQSTA5CNFSM4KLSULCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKITPSA#issuecomment-579942344>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADLUWJ6BEUWUZJKTCD54T7LRAHQSTANCNFSM4KLSULCA>
> .
>