Add STABILIZED_[YAW, ROLL, PITCH] for logic_condition
iNavFlight/inav pull request #5623
Opened 2020-04-25 17:35 UTC by joleeee

Let me know what needs to be changed.
Original issue: https://github.com/iNavFlight/inav/issues/5617

2020-04-25 17:40 UTC, joleeee commented
@pawelchcki Perhaps you could give some input on this? I understand you are the author of the logic conditions and probably have some opinions on implementation. I have tested a version of this and it works well. 

Also a picture of my servo setup:
![unknown](https://user-images.githubusercontent.com/24441708/80286582-84876d00-872c-11ea-941c-3753fcdcef61.png)

2020-04-25 18:03 UTC, DzikuVx commented
Quite impressive!

2020-04-25 18:04 UTC, DzikuVx requested changes

2020-04-25 18:04 UTC, DzikuVx commented on src/main/common/logic_condition.h
> +    LOGIC_CONDITION_OPERAND_FLIGHT_STABILIZED_YAW,                          // 26
@joleeee please reorder to ROLL PITCH YAW and we use this order everywhere.

2020-04-25 18:05 UTC, DzikuVx commented
also @joleeee do you think you could make the Configurator part? It's should we as simnple as adding those entries in one file

2020-04-25 21:49 UTC, joleeee commented
Done. https://github.com/iNavFlight/inav-configurator/pull/971

2020-04-26 09:19 UTC, DzikuVx approved these changes

2020-04-26 09:20 UTC, merged

2020-04-26 09:20 UTC, DzikuVx commented
thanks a lot