WIP: Multi gyro support
iNavFlight/inav pull request #5762
Opened 2020-05-19 18:45 UTC by jukkaaakko

WIP & experimental

2020-05-19 19:02 UTC, digitalentity requested changes
Review round 1.

I think we should treat read/calibration operations as using multiple sensors all the time - including averaging etc. Best approach would be to unify and decouple read/calibrate code from `gyroDev` alltogether.

I think we should have a list of gyros, but I can refactor that once we get iteration one working.

2020-05-19 19:02 UTC, digitalentity commented on src/main/sensors/gyro.c
> +            gyroDev[0].imuSensorToUse = gyroConfig()->gyro_to_use;
This is potentially unsafe if in future we introduce more possible values.

2020-05-19 19:02 UTC, digitalentity commented on src/main/fc/fc_msp.c
> +        sbufWriteU8(dst, gyroConfig()->gyro2_align);
This will require Configurator support as well. I recommend adding new fields to the end of MSP frame.

2020-05-19 19:02 UTC, digitalentity commented on src/main/fc/fc_msp.c
> +            gyroConfigMutable()->gyro2_align = sbufReadU8(src);
This is unsafe. If we receive a legacy frame of old format, this will cause incorrect values to be set. Move the new fields to the end of the frame and use `dataSize` to check if we have received an old/new frame and act accordingly.

2020-05-20 08:15 UTC, jukkaaakko commented on src/main/sensors/gyro.c
> +            gyroDev[0].imuSensorToUse = gyroConfig()->gyro_to_use;
True.  I think same applies to accelerometer also.

2020-05-20 08:32 UTC, jukkaaakko commented on src/main/fc/fc_msp.c
> +        sbufWriteU8(dst, gyroConfig()->gyro2_align);
I will remove gyro2_align and  acc2_align from fc_msp.

2020-06-10 19:21 UTC, closed without merging