[MAVLINK] Update flight modes map to match Arduplane/Arducopter
iNavFlight/inav pull request #5950
Opened 2020-07-15 15:53 UTC by machadofelipe

Fix for wrong flight modes being sent trough Mavlink.

While using OpenHD with my Fixed Wing and receiving telemetry to feed the OSD via Mavlink, I noticed that the flight modes were wrong most of the time. 
I noticed that the modes mapping in iNav to Ardupilot was probably old and not compliant with new modes. Also, the mapping was not type safe, meaning that new modes were messing with the working ones. 

Please, help me review this PR and guide me if you think that there is a better placement for the ardupilot enums (taken from ardupilotmega.h).

2020-07-15 19:48 UTC, digitalentity requested changes
A few minor nits, overall LGTM, thanks for looking into this!

2020-07-15 19:48 UTC, digitalentity commented on src/main/telemetry/mavlink.c
> +#ifndef HAVE_ENUM_PLANE_MODE
This is unnecessary

2020-07-15 19:48 UTC, digitalentity commented on src/main/telemetry/mavlink.c
> +typedef enum PLANE_MODE
Please rename this to i.e. `APM_PLANE_MODE` to indicate that it's not INAV's native enum

2020-07-15 19:48 UTC, digitalentity commented on src/main/telemetry/mavlink.c
> +typedef enum COPTER_MODE
Same as above, rename to `APM_COPTER_MODE`

2020-07-15 19:48 UTC, digitalentity commented on src/main/telemetry/mavlink.c
> +#define HAVE_ENUM_COPTER_MODE
Remove this

2020-07-15 20:32 UTC, machadofelipe commented
Sure, did some changes already.
Let me know if there is anything else, as this is not about the fix, but to learn the process/conventions around iNav. This is only the first commit yet ;)

2020-07-16 07:39 UTC, digitalentity approved these changes

2020-07-16 07:40 UTC, digitalentity commented
@machadofelipe looks good, thanks!

2020-07-19 19:03 UTC, merged

2021-02-14 15:41 UTC, kasatka60 commented
Today I flew a wing with a openhd and the inav does not transmit the coordinates of the launch point during the arm.

2021-02-14 17:51 UTC, machadofelipe commented
> Today I flew a wing with a openhd and the inav does not transmit the coordinates of the launch point during the arm.

hi @kasatka60 , OpenHD has its own way of setting Home Position, it should work as long as you have Ground unit connected before you arm with enough GPS strength. iNav sends "global_origin" and openhd is not making using of this message. That can be a future change for QOpenHD, not iNav.