[MAVLINK] Add new mavlink messages
iNavFlight/inav pull request #6062
Opened 2020-08-21 22:42 UTC by machadofelipe

![20200821_231832](https://user-images.githubusercontent.com/6013351/90940421-95a86800-e406-11ea-9d07-418be063bf5a.gif)

Hi devs, this adds a new mavlink data stream at 1Hz. This is crucial to have system messages for systems such as OpenHD.

1. Update throttle to also show navigation thr;
2. Send battery cell count and consumption in battery status;
3. Send baro or imu temperature in scaled pressure sensor;
4. Send same OSD system msg as status text.

Please, let me know if I can improve this commit. The messages are based on OSD functions and a bit duplicated, but I saw no better way to avoid messing with the OSD.

If possible, let me know your thoughts about updating iNav to the new Mavlink v2 and also including some msgs from ardupilot dialect. That way we could send ESC temperatures and Wind estimation via Mavlink.

2020-08-22 07:12 UTC, digitalentity requested changes

2020-08-22 07:12 UTC, digitalentity commented on src/main/telemetry/mavlink.c
> +static const char * mavlinkArmingDisabledReasonMessage(void)
I think this PR would be the right time to unify the status text generation - it's shared between OSD and MAVLINK anyway. WDYT?

2020-08-23 22:05 UTC, machadofelipe commented on src/main/telemetry/mavlink.c
> +static const char * mavlinkArmingDisabledReasonMessage(void)
Yes, sure, makes sense. Will do the changes them over the next weekend. This week I am out flying iNav in summer camping 😉

2020-08-30 13:52 UTC, machadofelipe commented
Updated the PR. Please review and let me know if I can improve.
Tested both in bench as in the air with MATEKF405SE + QOpenHD and wifibroadcast-osd

Below is the full list of changes:
- Did the integration with the OSD system messages. For now the added Mavlink Status Text is limited to boards with OSD active, but in a short future I will try to generalize this part a bit more.
- Break down the failsafe mode to map real ardu modes. When no Receiver is active and mode in iNav is only "Failsafe", there is no real correpondent mode in Ardupilot.
- In the future it maybe better to do a getMode just for mavlink and find the correct mode without using mapping.
- Added sensors health report. Very useful for alarms in ezwifibroadcast and old osd in OpenHD.
- Correct heading to centidegrees added velocity per axis in global_position, as required from mavlink lib.
- Throttle telemetry reflects the signal used to command (includes navigation throttle).
- Added message to send battery status with cell average, number of cells, current consumed and energy consumed.
- Added baro temperature if available or send Imu temp. instead.
- For the new messages, a new telemetry stream (extra3) was added.
- Mavlink library update to latest release in v1.0 (better documented and less magic numbers overall)

2020-09-15 21:12 UTC, machadofelipe commented
@digitalentity should I change anything to help the review process?

2020-09-17 06:00 UTC, digitalentity commented
Sorry, this fell through the cracks. Will have a look later on today.

2020-10-06 08:13 UTC, digitalentity approved these changes
LGTM from me. @fiam can you have a second look at the changes in the OSD messages code?

2020-10-10 09:52 UTC, merged