Add "prearm was reset" flag to prevent rearming without resetting prearm
iNavFlight/inav pull request #6737
Opened 2021-03-24 16:47 UTC by harry1453

This fixes an oversight in my implementation of Prearm: Once prearm is held, you can toggle the arm switch on and off all day. So if a non-momentary prearm is used and the quad is disarmed without resetting the prearm, it can be armed again with the single arm switch, which defeats the prearm.

This PR adds a simple flag to track whether the prearm has been reset (not engaged / RC mode not active) since the last disarm.

I don't like the alternative suggestion of adding a prearm timer, I feel like it will become frustrating and does not solve the issue for short arming sequences (test arms)

2021-03-31 19:34 UTC, DzikuVx requested changes

2021-03-31 19:34 UTC, DzikuVx commented on src/main/fc/rc_controls.h
> +    uint16_t prearmTimeoutMs;               // duration for which Prearm being activated is valid. after this, Prearm needs to be reset. 0 means Prearm does not timeout.
You have to increase the parameter group version when you add a new field.
See fine `rc_controls.c` line 72

2021-03-31 19:34 UTC, DzikuVx commented on src/main/fc/rc_controls.h
> +    uint16_t prearmTimeoutMs;               // duration for which Prearm being activated is valid. after this, Prearm needs to be reset. 0 means Prearm does not timeout.
Also, you should set the default value of the new parameter group field

2021-04-05 09:12 UTC, merged

2024-02-29 09:25 UTC, sdellava commented
I guess this issue is still not resolved. pleas check this: https://github.com/iNavFlight/inav/issues/9752