OSD sidebar height option
iNavFlight/inav pull request #6896
Opened 2021-04-27 13:22 UTC by breadoven

One issue with the current  character based OSD sidebars is they take up a lot of space for limited benefit. However, one of the most useful elements of the sidebars, the level indicator arrow that provide a reference for the artificial horizon, are lost if you turn the sidebars off. To get around this problem this PR provides a setting to change the OSD sidebar height. It can be set between 0 to 5 rows, default 3 as now. Setting to 0 completely removes the sidebars leaving just the level indicator arrows.

Although this change could be applicable for the pixel OSD it's currently limited to the character OSD because I don't have a pixel OSD to test. Perhaps if this can be tested, in particular for a height of 0 (set by `OSD_AH_SIDEBAR_HEIGHT_POS `) then this change could be updated to include the pixel OSD.

2021-04-27 14:58 UTC, DzikuVx requested changes
@breadoven we have to increase the Parameter Group. in osd.c around line 196

`PG_REGISTER_WITH_RESET_TEMPLATE(osdConfig_t, osdConfig, PG_OSD_CONFIG, 0);`

2021-04-27 18:22 UTC, breadoven commented
OK, PG updated DzikuVx.

2021-04-28 07:36 UTC, DzikuVx approved these changes

2021-05-03 15:06 UTC, merged

2021-05-18 20:55 UTC, b14ckyy commented
@breadoven can you check if your change causes #6990? 
Just a guess.