add esc temperatur on cli status
iNavFlight/inav pull request #7094
Opened 2021-06-07 23:07 UTC by Christoph-Hofmann

Show ESC temperatures from each esc.
So you can easily see that telemetry from all escs is working.

2021-06-08 10:44 UTC, DzikuVx approved these changes

2021-06-09 15:22 UTC, JulioCesarMatias commented on src/main/fc/cli.c
> +    uint8_t motorCount = getMotorCount();
There is a check missing to only print this in the case that the user has configured the ESC sensors - no point printing it when there is no data to print.

2021-06-09 15:29 UTC, JulioCesarMatias commented
What need is there to check the esc temperature in the CLI where the motors won't even be spinning and the temp will just be the base idle value for the esc?

2021-06-09 15:31 UTC, JulioCesarMatias commented
The `status` command is used for users to provide status information when helping developers to debug a problem - this information is unrelated to this task, and will only add confusion, so even if the CLI is the right place for your use case, `status` isn't the right command.

2021-06-09 15:33 UTC, JulioCesarMatias commented
In my opinion, this should be moved from the CLI, to somewhere in the iNav-Configurator.

2021-06-09 21:51 UTC, Christoph-Hofmann commented
That the easy way to see, if all esc's are sending teletry values.
In the OSD you see only the highest temperature.
So it's for debugging purpose.

2021-06-09 22:04 UTC, JulioCesarMatias commented
> That the easy way to see, if all esc's are sending teletry values.
> In the OSD you see only the highest temperature.
> So it's for debugging purpose.

hello, sorry for the mistake, i didn't realize it was through telemetry. Disregard my comments

2021-06-13 16:45 UTC, DzikuVx requested changes

2021-06-13 16:45 UTC, DzikuVx commented on src/main/fc/cli.c
> +    cliPrintLinef("ESC Temperature(s): Motor Count=%d",motorCount);
@Christoph-Hofmann this is a very cool addition. I always struggle to verify if ESC telemetry works.
Let's however, improve it and display this line onli if 
`if (STATE(ESC_SENSOR_ENABLED) && getMotorCount() > 0) {`

2021-06-13 16:53 UTC, avsaase commented
How about just showing `ESC TELEM = OK` when telemetry is received. I agree with @JulioCesarMatias that the actual temperature values aren't that interesting on the bench. This could also be added to the configurator with the other sensors.

2021-06-15 13:35 UTC, rmaia3d commented
> How about just showing `ESC TELEM = OK` when telemetry is received. I agree with @JulioCesarMatias that the actual temperature values aren't that interesting on the bench. This could also be added to the configurator with the other sensors.

Nooo, they are interesting and important on the bench as well!! It's a good and quick way to determine if an ESC is going bad (or there's a short or anything else wrong with the connections) before the magic smoke is let out...

2021-06-15 21:15 UTC, JulioCesarMatias commented
> The `status` command is used for users to provide status information when helping developers to debug a problem - this information is unrelated to this task, and will only add confusion, so even if the CLI is the right place for your use case, `status` isn't the right command.

.

2021-06-15 21:15 UTC, JulioCesarMatias commented
> In my opinion, this should be moved from the CLI, to somewhere in the iNav-Configurator.

.

2021-06-26 09:08 UTC, DzikuVx commented
@JulioCesarMatias if you could update the PR with requested changes, I'd like to merge it to `master` quite soon

2021-06-28 08:34 UTC, DzikuVx commented
Replaced by #7200
Thanks a lot to all the participants

2021-06-28 08:34 UTC, closed without merging