Flip32 F4 target
iNavFlight/inav pull request #717
Opened 2016-10-23 15:59 UTC by DzikuVx

Flip32 F4 / Airbot F4 target. This is Revo target with few changes.

Depends on updated Revo target ( #688 )

- [ ] verify I2C working
- [ ] add all supported I2C hardware
- [ ] verify GPS
- [ ] verify RSSI working
- [ ] verify LED working, move to dedicated pins if possible

2016-10-23 19:02 UTC, nathantsoi commented
note, this is also the same as the omnibusf4, which adds the max chip, when osd support is added to inav

2016-10-23 19:03 UTC, nathantsoi commented
sweet, nice work! note that this is also the same as the omnibusf4, which adds the max chip, when osd support is added to inav. and an fyi, we decided in betaflight to make the airbot f4 / flip 32 work w/ the revo target.

2016-10-23 19:21 UTC, DzikuVx commented
@nathantsoi We need I2C for Baro/Mag/WhateverElse and current implementation does not work for both original Revo and Flip32F4. 
See #718 an #719 
With #718 it would be possible to merge revo and flip32f4 again

2016-10-24 10:51 UTC, DzikuVx commented
@nathantsoi Update: because build in Revo mag and baro uses I2CDEV_1 and Flip32F4 and derivatives does not have built in baro and mag and only I2CDEV_2 is available it would be impossible to use them in Revo target.
Even when 2 buses will be implemented, board would try to use I2CDEV_1 for them even when they are on I2CDEV_2
So new target is requires after all

2016-10-24 11:34 UTC, DzikuVx commented on src/main/main.c
> +#elif defined(I2C_DEVICE_SHARES_UART3)
@digitalentity @martinbudden that's my idea of removing some target dependencies in main.c

2016-10-24 11:37 UTC, digitalentity commented on src/main/main.c
> +#elif defined(I2C_DEVICE_SHARES_UART3)
I think we need to be smarter - let the per-target code decide what is available.

2016-10-24 19:02 UTC, DzikuVx commented
Either REVO target is wrong, or this board is not REVO clone after all. Motor 6 is not connected to PA0 like target file states, but PA8. That is actually good, since it allows RSSI ADC and Motor 6 to be used at the same time.

LED strip not working, reason unknown

2016-10-25 06:45 UTC, martinbudden commented
@DzikuVx , have you tried LED strip with blackbox turned off. In betaflight there have been some issues of DMA clashing (both LED strip and blackbox use DMA), so a similar thing might be occurring here.

Also, stating the obvious, I presume you have also checked the pin for motor 5?

2016-10-25 07:46 UTC, DzikuVx commented
No, did not tried without Blackbox enabled. Will check that today.

Yes, I checked pin for motor 5, checked timer clashes and all that stuff. Since I do not see it as primary function, it can be published even with LED disabled

2016-10-25 08:12 UTC, martinbudden commented
I agree, we can add this target without LED strip, as long as it's clearly stated in the release notes.

It would be good to find out what is going on though.

2016-10-25 18:21 UTC, DzikuVx commented
I suspect led driver on our side. In bf 3.0.1 it is working, but have to
recheck 3.1

wt., 25.10.2016, 10:12 użytkownik Martin Budden <notifications@github.com>
napisał:

> I agree, we can add this target without LED strip, as long as it's clearly
> stated in the release notes.
>
> It would be good to find out what is going on though.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/iNavFlight/inav/pull/717#issuecomment-255967460>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA7AmwjANKBwHGyaq7CBxsl6B2FbjkQ-ks5q3boBgaJpZM4KeKwm>
> .
>
-- 
Pozdrawiam,
Paweł Spychalski

2016-10-25 18:22 UTC, DzikuVx commented
@digitalentity ready for merge into 1.4
LED Strip not working...

2016-10-29 14:12 UTC, DzikuVx commented
Flight tested with async gyro.... I love it :)

2016-11-02 10:56 UTC, digitalentity requested changes

2016-11-02 10:56 UTC, digitalentity commented on src/main/target/FLIP32F4/target.h
> +#define LED_STRIP
Since LED_STRIP is not working should't we disable it?

2016-11-02 10:58 UTC, DzikuVx commented on src/main/target/FLIP32F4/target.h
> +#define LED_STRIP
Yes, you are right. I will disable it

2016-11-02 11:02 UTC, DzikuVx commented on src/main/target/FLIP32F4/target.h
> +#define LED_STRIP
@digitalentity  and done

2016-11-02 11:14 UTC, digitalentity approved these changes

2016-11-02 14:41 UTC, DzikuVx commented
OK, it will not be any better than is right now, I'm merging it

2016-11-02 14:42 UTC, merged