Update Board - MatekF405 Wing.md
iNavFlight/inav pull request #7315
Opened 2021-07-28 20:07 UTC by JuliusZimbovsky

added link to  matek board photo

2021-07-28 21:04 UTC, JulioCesarMatias commented
LGTM! Pawel link is broken.

2021-07-29 06:30 UTC, DzikuVx requested changes

2021-07-29 06:30 UTC, DzikuVx commented on docs/Board - MatekF405 Wing.md
> +![Matek F405 Wing](http://www.mateksys.com/?portfolio=f405-wing)
Well, this a website link, while we expect image URL over here. Please update to point to image, not website

2021-07-30 00:21 UTC, JulioCesarMatias commented
this image seems to me to be the best:

http://www.mateksys.com/wp-content/uploads/2018/04/F405-WING_Layout-1471x1500.jpg

2021-07-30 00:23 UTC, JulioCesarMatias commented
> LGTM! Pawel link is broken.


I didn't realize that the link went to Matek's website, I thought it went to a direct image. Sorry

2021-09-18 08:55 UTC, closed without merging