Adding loiter radius to programming
iNavFlight/inav pull request #7480
Opened 2021-09-25 21:29 UTC by MrD-RC

Adding a loiter radius override to the programming. This change allows pilots to change their loiter radius on the fly. The minimum loiter radius will always be that set in Advanced Tuning, for safety. The maximum radius is 100000cm.

This is basically the change that I started working on as discussed in https://github.com/iNavFlight/inav/issues/6237

Requires 

Fixes #5968 https://github.com/iNavFlight/inav/projects/4#card-44998146

Example programming
![image](https://user-images.githubusercontent.com/17590174/134786183-806615b8-ad7a-484a-8a04-a8c17c4622ff.png)
- The yellow area shows a simple set of the loiter radius by using a switch position. Here is it is trying to see to 10Km, which fails and sets the limit to the maximum value, currently 1000m. In my testing I set this to 50000.
- The purple area show programming to allow the loiter radius to be set by a pot. This example changes the loiter radius in 10m steps. In my testing I tweaked this further to start at 5000 and go up to 25000.
- The green area shows an example of setting GV0 to the loiter radius in metres. This can then be shown on the OSD.

In my test I has a 3 position switch. Position 1 was off. This uses the standard loiter radius set in iNav, Position 2 enabled the left slider to set a loiter radius. You can see this in operation for most of the video. The third position set the loiter radius to 50000 (500m).

Video of this is action: https://youtu.be/LF6cbMongTY

I will perform another test tomorrow and remember to use the blackbox. It would be good to see this tracked on a map. But, It it visibly working fine, based on the distance to the water when the radius changes. It also appears to keep the centre point of the loiter circle, as shown when I switch from 500m to 50m.

Note: As part of this change, I increased the min and max constraints of the basic maths conditions. The were set to int16, however operands can be int32. Before the change, this caused clipping of the radius when performing basic calculus on it.

2021-09-26 16:44 UTC, MrD-RC commented
Went for another flight today. I need to add some code so that the loiter radius is only adjusted in pos hold. Currently it effects RTH too, which can cause the RTH to miss the home point.

The wind was pretty gusty today, which caused the wing to struggle keeping the loiter and altitude. Here is the plot of the 2 loiter radii that I used: 50m and 250m. I'll upload a video to accompany the map plot shortly.
![Mini AR test Wind](https://user-images.githubusercontent.com/17590174/134816491-0e666543-8595-4a76-a32f-26b3fdfaf135.jpg)

2021-09-26 18:50 UTC, MrD-RC commented
Added code to only override the loiter radius in NAV POS HOLD.

Tested on the bench. Will hopefully test in flight next weekend.

2021-10-20 20:16 UTC, DzikuVx requested changes

2021-10-20 20:16 UTC, DzikuVx commented on src/main/navigation/navigation_fixedwing.c
> +    uint32_t navLoiterRadius = navConfig()->fw.loiter_radius;
Can we have separate declaration for `USE_PROGRAMMING_FRAMEWORK` defined and not defined? So we do not override immediately after initialization? Or even better! Make the condition part of `getLoiterRadius` itself?

So

```
uint32_t getLoiterRadius(uint32_t loiterRadius) {
#ifdef

#else

#endif

}
```

2021-10-20 20:16 UTC, DzikuVx commented on src/main/programming/logic_condition.c
> +            return constrain(operandA + operandB, INT32_MIN, INT32_MAX);
Can we then change all variables that hold the result of `logicConditionCompute` to `int32_t` instead of `int` ? That would look better I think

2021-10-20 22:02 UTC, MrD-RC commented on src/main/navigation/navigation_fixedwing.c
> +    uint32_t navLoiterRadius = navConfig()->fw.loiter_radius;
Actually, having the `#IFDEF` in the function would be much neater. Done.

2021-10-20 22:03 UTC, MrD-RC commented on src/main/programming/logic_condition.c
> +            return constrain(operandA + operandB, INT32_MIN, INT32_MAX);
Done.

2021-10-28 06:18 UTC, DzikuVx approved these changes

2021-10-28 06:20 UTC, merged