mlx90393 support added
iNavFlight/inav pull request #7533
Opened 2021-10-22 16:54 UTC by Elkin-Vasily

closes #6000

2021-10-24 17:01 UTC, JulioCesarMatias commented on src/main/drivers/compass/compass_mlx90393.h
> + * This file is part of Cleanflight.
change "Cleanflight" to "iNav"

2021-10-24 17:01 UTC, JulioCesarMatias commented on src/main/drivers/compass/compass_mlx90393.c
> + * This file is part of Cleanflight.
change "Cleanflight" to "iNav"

2021-10-26 07:54 UTC, DzikuVx requested changes

2021-10-26 07:54 UTC, DzikuVx commented on src/main/drivers/compass/compass_mlx90393.c
> +static void mlx_write_register(magDev_t * mag, uint8_t reg_val, uint16_t value) {
Can we please use camelCase over here as well?

2021-10-26 15:05 UTC, Elkin-Vasily commented on src/main/drivers/compass/compass_mlx90393.c
> +static void mlx_write_register(magDev_t * mag, uint8_t reg_val, uint16_t value) {
Done

2021-10-26 19:09 UTC, DzikuVx approved these changes

2021-10-28 06:24 UTC, merged