Add ability to adjust LED Strip color with RC channel
iNavFlight/inav pull request #7618
Opened 2021-11-19 20:00 UTC by jeffhendrix

Add ability to adjust LED Strip color with RC channel by using H in led cli (see LedStrip.md)
closes #7556

2021-11-22 08:40 UTC, DzikuVx approved these changes

2022-01-09 02:10 UTC, jeffhendrix commented
Got a notice that this will be closed in two weeks if no activity occurs with it

2022-01-09 09:06 UTC, DzikuVx commented
No, not this one. StaleBot has not touched this one

2022-01-10 16:34 UTC, DzikuVx commented
closes #4481

2022-02-22 13:19 UTC, DzikuVx commented
@jeffhendrix as it's time to start merging, I have a question. Do we need a Configurator support for this one?

2022-02-22 20:14 UTC, jeffhendrix commented
Not needed, but makes it easier to configure.
Here is the PR for configurator changes
https://github.com/iNavFlight/inav-configurator/pull/1406

On Tue, Feb 22, 2022 at 6:19 AM Paweł Spychalski ***@***.***>
wrote:

> @jeffhendrix <https://github.com/jeffhendrix> as it's time to start
> merging, I have a question. Do we need a Configurator support for this one?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/iNavFlight/inav/pull/7618#issuecomment-1047789216>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABVNCLVTUOTZZYA5NLTYWDDU4OEN7ANCNFSM5IM47SPA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-23 08:10 UTC, DzikuVx requested changes
@jeffhendrix one final request, we have to bump parameter group version in src/main/io/ledstrip.c on line 76 
The config structure changes so version has to change as well

2022-02-24 08:32 UTC, merged