[settings.yaml] Clear GPS Provider list
iNavFlight/inav pull request #8102
Opened 2022-06-07 20:42 UTC by JulioCesarMatias

Remove the value `UNUSED` from list

2022-06-07 21:03 UTC, JulioCesarMatias commented
> Requires update to `src/main/io/gps.h` and possibly the configurator

![Captura de tela 2022-06-07 180223](https://user-images.githubusercontent.com/25625982/172482077-0d86e48e-7114-4a79-8ada-e6d0d68a7d9a.jpg)
is strange, because Enum is the same as Box in Configurator

2022-06-07 21:04 UTC, JulioCesarMatias commented
> Requires update to `src/main/io/gps.h` and possibly the configurator


thanks

2022-06-08 06:51 UTC, DzikuVx requested changes
We also would need a PG version bump in `PG_REGISTER_WITH_RESET_TEMPLATE(gpsConfig_t, gpsConfig, PG_GPS_CONFIG, 0);`

2022-06-09 05:53 UTC, DzikuVx approved these changes

2022-06-17 08:39 UTC, merged