[cli.c] RC map code aesthetics
iNavFlight/inav pull request #8153
Opened 2022-06-23 21:40 UTC by JulioCesarMatias

2022-06-24 09:05 UTC, DzikuVx requested changes
Nice cleanup, but I think we can slightly improve it. WDYT @JulioCesarMatias ?

2022-06-24 09:05 UTC, DzikuVx commented on src/main/fc/cli.c
> +        for (uint32_t i = 0; i < len; i++) {
I think it would make more sense to have it as

`for (uint32_t i = 0; i < MAX_MAPPABLE_RX_INPUTS; i++)`

2022-06-24 20:26 UTC, JulioCesarMatias commented on src/main/fc/cli.c
> +        for (uint32_t i = 0; i < len; i++) {
done!

2022-06-26 10:09 UTC, DzikuVx approved these changes

2022-06-26 10:09 UTC, merged