Support for Flash Memory W25N01G of 128MB
iNavFlight/inav pull request #8166
Opened 2022-06-26 23:40 UTC by JulioCesarMatias

Along with @robustini and @hogthrob, I'm trying to bring this support to iNav, countless FC are currently using this flash memory.

- [ ] Add the drivers
- [ ] Make FC read multiple flash memories (added by @hogthrob).
- [ ] Make W25N01G memory work regardless of whether M25P16 is set or not.
- [ ] Fix FC crash if flash memory is not found (For some reason user removed from FC PCB, or it burned).
- [ ] Make Reading and Writing work

2022-06-27 05:51 UTC, robustini commented
The dataflash is correctly detected, at the moment it is not possible to write or read.
I tested it with this [commit](https://github.com/iNavFlight/inav/commit/101e345b4f21afe2319c0235d0762082126a9d09) as well.

![immagine](https://user-images.githubusercontent.com/3864712/175868592-f0fb21cd-5b1c-4280-bf93-1d7e53e00efb.png)

2022-06-27 06:44 UTC, DzikuVx commented
That is awesome, thanks a lot for starting to work on it @JulioCesarMatias

2022-06-28 00:14 UTC, JulioCesarMatias commented
@DzikuVx Can we add the `Release Notes` label to this PR?

2022-06-28 06:09 UTC, MrD-RC commented
Can you add a section in the PR description with a release notes heading. Under that, write what should be included in the release notes. It just makes creating the releases easier.

2022-06-28 06:36 UTC, robustini commented
@JulioCesarMatias thanks for the latest updates, i compiled with that PR but it still doesn't work.

https://user-images.githubusercontent.com/3864712/176109862-649e4334-b37a-4718-8226-78eb0b614ecf.mp4

2022-06-28 13:27 UTC, hogthrob commented
@robustini : The code in my branch does erase successfully, so this is an indication that there is a problem in @JulioCesarMatias code. BTW, "erase" is not equal "writing", these are completely different operations. That one works doesn't imply the other does. 

However, in my branch (not @JulioCesarMatias PR which you tested), everything (read, write, erase) is working. 
Also blackbox recording (and display of amount of logged data aka free space) is working, although I "armed" the device for that.
Wasn't aware the logging also works unarmed.
 
Unfortunately, in my branch saving the blackbox log from flash is not working, though. I can see the log being written when I inspect the content using the low level `flash_read` cli command (#define USE_FLASH_TOOLS reguired in target.h) but the blackbox UI is not saving it for unknown reasons. 

@JulioCesarMatias code from this PR (not taking from the PR but his branch, though) does not produce working code for the MAMBAH743 target when I build this on my machine. That may not be the fault of the his changes but coming from the master branch but I didn't have the time to check this.

2022-06-28 13:38 UTC, robustini commented
> @robustini : The code in my branch does erase successfully, so this is an indication that there is a problem in @JulioCesarMatias code. BTW, "erase" is not equal "writing", these are completely different operations. That one works doesn't imply the other does.
> 
> However, in my branch (not @JulioCesarMatias PR which you tested), everything (read, write, erase) is working. Also blackbox recording (and display of amount of logged data aka free space) is working, although I "armed" the device for that. Wasn't aware the logging also works unarmed.
> 
> Unfortunately, in my branch saving the blackbox log from flash is not working, though. I can see the log being written when I inspect the content using the low level `flash_read` cli command (#define USE_FLASH_TOOLS reguired in target.h) but the blackbox UI is not saving it for unknown reasons.
> 
> @JulioCesarMatias code from this PR (not taking from the PR but his branch, though) does not produce working code for the MAMBAH743 target when I build this on my machine. That may not be the fault of the his changes but coming from the master branch but I didn't have the time to check this.

yes, I get confused with Betaflight where BlackBox is configurable in ALWAYS and logs even when unarmed.

2022-06-29 06:55 UTC, robustini commented
Tested now with the latest fix and flashgo, it hangs on reading them:

![immagine](https://user-images.githubusercontent.com/3864712/176371006-2753f977-3e3c-4b04-98b1-f1dcdbb0eee1.png)

2022-07-01 19:25 UTC, DzikuVx commented
@JulioCesarMatias when ready to merge, please squassh to a single commit if possible. I will want to cherry-pick it to 5.1 branch

2022-07-01 20:08 UTC, hogthrob commented
I pushed my working code to my repository https://github.com/hogthrob/inav/tree/flash_w25n01gSupport , see discussion in  #8098 (work is based on this branch). No need to create an additional PR, let's wait for the report of @robustini .

BTW, still fighting to find the correct formatting setting for VS Code to match iNav formatting exactly style.

2022-07-01 21:15 UTC, JulioCesarMatias commented
> I pushed my working code to my repository https://github.com/hogthrob/inav/tree/flash_w25n01gSupport , see discussion in #8098 (work is based on this branch). No need to create an additional PR, let's wait for the report of @robustini .
> 
> BTW, still fighting to find the correct formatting setting for VS Code to match iNav formatting exactly style.

Very nice @hogthrob, this PR owes all the credits to you! I passed the changes to my branch, could you test it to make sure I didn't miss anything? >> https://drive.google.com/file/d/16iB-P9WEMapCN6pCEl2jhhyyRF_O3oPi/view?usp=sharing

2022-07-01 21:19 UTC, JulioCesarMatias commented
@hogthrob About the "dummy" flash you added, I preferred not to keep it, it is interesting yes, but visually it pollutes the algorithm... I think just checking that there is no flash memory on the FC PCB (even defined in target.h) , just indicating to the algorithm that it was not found is enough.

2022-07-01 21:54 UTC, hogthrob commented
There is a couple of places outside flash.c  calling various functions from flash.c are without checking if the flash was detected. Having such a dummy is the easiest way to get around this until this problem has been mitigated.

The other solution is to guard  every relevant call with along the lines `if (flash_not_found) { return default_answer; } else { flash->,,, }` . One could also call this pollution. 

But honestly, I don't care as long as the resulting code works, It is "your" project and your PR.

2022-07-01 22:21 UTC, JulioCesarMatias commented
@hogthrob Did the algorithm compiled through my branch work?

2022-07-02 06:34 UTC, robustini commented
> I pushed my working code to my repository https://github.com/hogthrob/inav/tree/flash_w25n01gSupport , see discussion in #8098 (work is based on this branch). No need to create an additional PR, let's wait for the report of @robustini .
> 
> BTW, still fighting to find the correct formatting setting for VS Code to match iNav formatting exactly style.

Doesn't see the dataflash here.
I attach the modified target.c for my board, it should be correct.

[target.zip](https://github.com/iNavFlight/inav/files/9032565/target.zip)

2022-07-02 06:44 UTC, robustini commented
> I pushed my working code to my repository https://github.com/hogthrob/inav/tree/flash_w25n01gSupport , see discussion in #8098 (work is based on this branch). No need to create an additional PR, let's wait for the report of @robustini .
> 
> BTW, still fighting to find the correct formatting setting for VS Code to match iNav formatting exactly style.

Doesn't see the dataflash here.
Hope my target.h is correct.

[target.zip](https://github.com/iNavFlight/inav/files/9032572/target.zip)

2022-07-02 07:08 UTC, robustini commented
> I pushed my working code to my repository https://github.com/hogthrob/inav/tree/flash_w25n01gSupport , see discussion in #8098 (work is based on this branch). No need to create an additional PR, let's wait for the report of @robustini .
> 
> BTW, still fighting to find the correct formatting setting for VS Code to match iNav formatting exactly style.

I compile in and I report the only anomaly.
Excuse the perhaps trivial question but in iNav there is the possibility to write on the blackbox unarmed as with Betaflight?
Here at home at the moment I don't have tx and battery and I can't test the writes in the dataflash if it doesn't do it unarmed.

![immagine](https://user-images.githubusercontent.com/3864712/176990538-2315fb41-2cff-40a3-a6fa-8fa1822f0fe6.png)

2022-07-02 07:15 UTC, robustini commented
@hogthrob no, there is still something wrong, it hangs here.

![immagine](https://user-images.githubusercontent.com/3864712/176990747-1dd64137-fed9-4ef4-bd4f-c6788bfd0b9a.png)

2022-07-02 07:34 UTC, stronnag commented
Couple of observations, apologies if they are trivial / stuff you already know / have tried.

* flashgo  has a hard coded read size of 4KB; would it help if this were configurable ?
* If you put blackbox on a switch, does that get around the arming requirement ?
* Can you see / read the flash in `MSC` mode ?
* FYI, mwptools includes a [CLI based flash downloader]( https://github.com/stronnag/mwptools/blob/master/src/samples/flash_dump.rb), if that's any automation help

2022-07-02 07:37 UTC, robustini commented
> Couple of observations, apologies if they are trivial / stuff you already know / have tried.
> 
>     * flashgo  has a hard coded read size of 4KB; would it help if this were configurable ?

It is probable

> 
>     * If you put blackbox on a switch, does that get around the arming requirement ?

No

> 
>     * Can you see / read the flash in `MSC` mode ?

No, it recognizes a device without a driver

> 
>     * FYI, mwptools includes a [CLI based flash downloader](https://github.com/stronnag/mwptools/blob/master/src/samples/flash_dump.rb), if that's any automation help

2022-07-02 08:48 UTC, stronnag commented
FWIW, now you can specify the read size, don't think it will help you:

```
$ flashgo -test
Using /dev/ttyACM0
Read buffer size 4096 bytes
Firmware: INAV
Version: 5.0.0
Entering test mode for 2097152b
Data flash 2097152 / 2097152 (100%)
Downloading to bbl_2022-07-02_093606.TXT
[▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇] 2.0MB/2.0MB 100% 0s
2097152 bytes in 38.5s, 54521.0 bytes/s
$ flashgo -test -readsize 8K
Using /dev/ttyACM0
Read buffer size 8192 bytes
Firmware: INAV
Version: 5.0.0
Entering test mode for 2097152b
Data flash 2097152 / 2097152 (100%)
Downloading to bbl_2022-07-02_093705.TXT
[▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇] 2.0MB/2.0MB 100% 0s
2097152 bytes in 39.1s, 53651.3 bytes/s
$ flashgo -test -readsize 1K
Using /dev/ttyACM0
Read buffer size 1024 bytes
Firmware: INAV
Version: 5.0.0
Entering test mode for 2097152b
Data flash 2097152 / 2097152 (100%)
Downloading to bbl_2022-07-02_093758.TXT
[▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇] 2.0MB/2.0MB 100% 0s
2097152 bytes in 49.3s, 42499.4 bytes/s
```

2022-07-02 10:09 UTC, robustini commented
> FWIW, now you can specify the read size, don't think it will help you:
> 
> ```
> $ flashgo -test
> Using /dev/ttyACM0
> Read buffer size 4096 bytes
> Firmware: INAV
> Version: 5.0.0
> Entering test mode for 2097152b
> Data flash 2097152 / 2097152 (100%)
> Downloading to bbl_2022-07-02_093606.TXT
> [▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇] 2.0MB/2.0MB 100% 0s
> 2097152 bytes in 38.5s, 54521.0 bytes/s
> $ flashgo -test -readsize 8K
> Using /dev/ttyACM0
> Read buffer size 8192 bytes
> Firmware: INAV
> Version: 5.0.0
> Entering test mode for 2097152b
> Data flash 2097152 / 2097152 (100%)
> Downloading to bbl_2022-07-02_093705.TXT
> [▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇] 2.0MB/2.0MB 100% 0s
> 2097152 bytes in 39.1s, 53651.3 bytes/s
> $ flashgo -test -readsize 1K
> Using /dev/ttyACM0
> Read buffer size 1024 bytes
> Firmware: INAV
> Version: 5.0.0
> Entering test mode for 2097152b
> Data flash 2097152 / 2097152 (100%)
> Downloading to bbl_2022-07-02_093758.TXT
> [▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇] 2.0MB/2.0MB 100% 0s
> 2097152 bytes in 49.3s, 42499.4 bytes/s
> ```

I tried but the problem remains, it doesn't depend on flashgo.

2022-07-02 10:28 UTC, stronnag commented
> I tried but the problem remains, it doesn't depend on flashgo.

I know, just though the option to at least easily try different read sizes might be useful.

2022-07-02 11:19 UTC, hogthrob commented
@robustini: target.h looks ok on the first glance. In the iNAV Configurator 'cli' what is the output of `flash_info` ?

2022-07-02 11:29 UTC, robustini commented
> @robustini: target.h looks ok on the first glance. In the iNAV Configurator 'cli' what is the output of `flash_info` ?

Flash sectors=1024, sectorSize=131072, pagesPerSector=64, pageSize=2048, totalSize=134217728
Paritions:
  0: BBMGMT    1003 1023
  1: FLASHFS   0 1002
FlashFS size=131465216, usedSize=0

2022-07-02 14:34 UTC, hogthrob commented
@robustini : That looks good. Flash is being detected properly. Now next thing to test is `flash_write 0 IwasHere`. Followed by `flash_write 2048 X`. Now `flash_read 0 16` should show you `IwasHere` plus 8 time a repeating character. 
With that correct operation of flash is confirmed. The rest is "just" setup. BTW, I haven't tried `flashgo` so maybe it is not working. But I am just now looking at my blackbox logs from some testflights I did earlier today.

2022-07-02 15:14 UTC, robustini commented
> flash_read 0 16


Entering CLI Mode, type 'exit' to return, or 'help'

# flash_write 0 IwasHere
Wrote 9 bytes at 0.

# flash_write 0 IwasHere
Wrote 9 bytes at 0.

# flash_write 0 IwasHere
Wrote 9 bytes at 0.

# flash_write 2048 X
Wrote 2 bytes at 2048.

# flash_read 0 16
Reading 16 bytes at 0:
 IwasHereÿÿÿÿÿÿÿ

2022-07-02 15:15 UTC, robustini commented
> @robustini : That looks good. Flash is being detected properly. Now next thing to test is `flash_write 0 IwasHere`. Followed by `flash_write 2048 X`. Now `flash_read 0 16` should show you `IwasHere` plus 8 time a repeating character. With that correct operation of flash is confirmed. The rest is "just" setup. BTW, I haven't tried `flashgo` so maybe it is not working.
> 
> But I am just now looking at my blackbox logs from some testflights I did earlier today, works for me.

`
Entering CLI Mode, type 'exit' to return, or 'help'

# flash_write 0 IwasHere
Wrote 9 bytes at 0.

# flash_write 0 IwasHere
Wrote 9 bytes at 0.

# flash_write 0 IwasHere
Wrote 9 bytes at 0.

# flash_write 2048 X
Wrote 2 bytes at 2048.

# flash_read 0 16
Reading 16 bytes at 0:
 IwasHereÿÿÿÿÿÿÿ
`

2022-07-02 15:57 UTC, hogthrob commented
@robustini :That confirms flash is working as it should. If you now reboot the flightcontroller, and run `flash_info` again, you should see the useSize increased to 2048.  And `flash_read 0 16` should still give you the same output.

All is left to go out and fly.

2022-07-02 16:09 UTC, robustini commented
@hogthrob very good, great job, thanks!
I repeat that however it would be useful to be able to log in even unarmed, I hope @DzikuVx can consider it as a feature.

2022-07-02 20:26 UTC, JulioCesarMatias commented
@robustini Can you test the Hex I compiled? >> https://drive.google.com/file/d/15-2fg1rZk6kw74PPS6gs8UjfcI5o0Scn/view?usp=sharing

2022-07-02 21:40 UTC, robustini commented
> @robustini Can you test the Hex I compiled? >> https://drive.google.com/file/d/15-2fg1rZk6kw74PPS6gs8UjfcI5o0Scn/view?usp=sharing

Good job mate! With your hex the MSC command work fine!
I can't test from CLI because you haven't put define for flash tools.

Flash sectors=1024, sectorSize=131072, pagesPerSector=64, pageSize=2048, totalSize=134217728
Paritions:
  0: FLASHFS   0 1023
FlashFS size=134217728, usedSize=0


![immagine](https://user-images.githubusercontent.com/3864712/177016847-1611ed86-66d8-497b-9149-00cd05cf0b52.png)

2022-07-02 22:30 UTC, hogthrob requested changes

2022-07-02 22:30 UTC, hogthrob commented on src/main/drivers/flash.c
> +    if (!flash->detected) {
This is not a perfectly safe approach to test for absence of flash, as this requires flashDeviceInit to have initialized the `flash` structure pointer before this check can be used. 
It also fails if flashfs (USE_FLASHFS) and none of the flash drivers are configured.
Easiest solution to this is to remove the `detected` field from the flash structure and put this as a static variable into the module flash.c and initialized with `false`. 
Added benefit of removing `detected` is that the flash structs array for the drivers could go to read-only memory (not RAM) if const is added to array definition as the function pointers do not change during run-time.

2022-07-02 22:48 UTC, JulioCesarMatias commented
@hogthrob what were the results after your commit? >> https://github.com/hogthrob/inav/commit/1bfada9c03c77ab064549b6f00b493152c9655a3

2022-07-02 22:50 UTC, hogthrob commented on src/main/drivers/flash.c
> +    if (!flash->detected) {
An alternative and probably the easiest solution is to use as test `if (flash == NULL)` as the flash variable only gets assigned if a driver was successfully initialized.

2022-07-03 00:45 UTC, JulioCesarMatias commented
@DzikuVx I don't know how to squash through Git, I made some attempts, but without success, and ended up compiling some things (such as doubling the number of commits of this PR)... But you can squash through the PR merge button

![github-close-pull-request-with-squash](https://user-images.githubusercontent.com/25625982/177020253-3b8d4722-0178-4ca1-a244-0b39ac98053c.png)

2022-07-03 01:26 UTC, JulioCesarMatias commented
@robustini I had some problems with the brach when trying to do a squash, and I had to edit some files manually again... so to make sure this is working could you test it again? >> https://drive.google.com/file/d/1KzXKr64IKQ42YMsrYYa9UenF6rkIWQQI/view?usp=sharing

2022-07-03 06:47 UTC, robustini commented
> @robustini I had some problems with the brach when trying to do a squash, and I had to edit some files manually again... so to make sure this is working could you test it again? >> https://drive.google.com/file/d/1KzXKr64IKQ42YMsrYYa9UenF6rkIWQQI/view?usp=sharing

It seems ok but I repeat it, at the moment I have not tested the writing and reading of a log file not being able to do it unarmed.

2022-07-03 10:15 UTC, robustini commented
I am now detecting a strange thing, the serialpassthrough command in CLI does not exist.
Having compiled from the master branch by merging this PR by chance in 6.0.0 this command from the CLI was removed?

2022-07-03 10:31 UTC, robustini commented
I'm trying to understand why my rx with ExpressLRS (CRFS protocol) with this firmware no longer communicates with the FC.
I flashed the official 5.0.0 it works correctly.
I had no problems when compiling the firmware.
I used the master branch plus this PR, nothing else.

2022-07-03 10:53 UTC, robustini commented
Tests completed, this is the feedback.
The CRSF problem with my board does not depend on this PR but present on the current master (6.0.0), I don't know if something has changed on the management of the rx, or something is broken.
However it is not a problem related to this PR.

2022-07-03 12:01 UTC, robustini commented
The compilation conflict is related to the CMakeLists.txt, "project (INAV VERSION 6.0.0)" in this PR while the branch version is 5.1.0.

2022-07-04 06:35 UTC, robustini commented
CRFS problem fixed with #8191.

2022-07-04 19:26 UTC, JulioCesarMatias commented
Okay, thanks to everyone involved. This work is ready to be merged!

2022-07-11 08:00 UTC, merged