Settings.md: Document osd_ahi_reverse_roll
iNavFlight/inav pull request #8167
Opened 2022-06-27 02:56 UTC by MorrisR2

2022-06-27 06:42 UTC, DzikuVx requested changes

2022-06-27 06:42 UTC, DzikuVx commented on docs/Settings.md
> +Switches the artificial horizon in the OSD to instead be a bank indicator, by reversing the direction of its movement.
@MorrisR2 the description has to be updated in the `settings.yml` and the generated using `python3 src/utils/update_cli_docs.py -q`

2022-06-27 21:55 UTC, MorrisR2 commented
This has been corrected as DzikuVx directed.

2022-06-28 08:25 UTC, DzikuVx approved these changes
Thanks!

2022-06-29 08:11 UTC, merged