[INS] Use Acc calibration validation instead of Gyro
iNavFlight/inav pull request #8214
Opened 2022-07-12 00:05 UTC by JulioCesarMatias

INS uses the `isImuReady()` function to calibrate the 1G of the acceleration. If the Acc is not calibrated, the INS should be inactive (which does not happen when checking the Gyro).

2022-07-12 05:46 UTC, DzikuVx requested changes

2022-07-12 05:46 UTC, DzikuVx commented on src/main/flight/imu.c
> +    return sensors(SENSOR_ACC) && STATE(ACCELEROMETER_CALIBRATED);
I think it should be rather extended to `sensors(SENSOR_ACC) && gyroIsCalibrationComplete() && STATE(ACCELEROMETER_CALIBRATED)`

2022-07-12 19:46 UTC, JulioCesarMatias commented
@DzikuVx Can we rename the function from `isImuReady()` to `imuIsHealth()` ?

2022-07-12 19:47 UTC, DzikuVx commented
@JulioCesarMatias but this function does not checks `health` only basic status of IMU. So not sure about renaming

2022-07-12 19:49 UTC, JulioCesarMatias commented
> ok, no problem, let's leave it the way it is

2022-09-22 11:17 UTC, DzikuVx approved these changes

2022-09-22 11:17 UTC, merged