Remove unnecessary parameters from profiles
iNavFlight/inav pull request #8451
Opened 2022-10-06 20:37 UTC by MrD-RC

`fw_loiter_direction` was in control profiles. There's no reason why this would want to be changed with different control parameters. It's purely a pilot preference. This has been moved to `navConfig.fw`

`fw_min_throttle_down_pitch` was in the battery profiles. This command is really something that is set based on the airframe and it's glide ratio. Battery type or performance does not effect this. Moved to `navConfig.fw`

2022-10-07 06:34 UTC, DzikuVx requested changes
We need PG version bump for all modified configs. Or we will be getting invalid settings when users upgrade without full chip erase

2022-10-07 12:12 UTC, MrD-RC commented
@DzikuVx Updated the PG. Think I need to get "Update PG" tattooed on my forehead 🤣

2022-10-14 20:27 UTC, shellixyz commented
`fw_min_throttle_down_pitch` is in the battery profiles because you can use batteries which don't have the same weight and so need a different value for this setting

2022-10-15 08:56 UTC, b14ckyy commented
@shellixyz I don't think this is correct.
the weight of the battery has no influence on the glide angle. only the glide speed but so does a lighter battery reduce the stall speed. 

a heavier battery raises the stall speed but also makes the glide faster at the same angle. 

only the aerodynamics of the plane dictate the glide angle. any real airplane has also a fixed glide ratio no matter if the fuel tanks are full or not.

2022-10-15 15:26 UTC, shellixyz commented
> @shellixyz I don't think this is correct. the weight of the battery has no influence on the glide angle. only the glide speed but so does a lighter battery reduce the stall speed.

Ok, you convinced me, it's fine to move it then

2022-11-27 12:15 UTC, merged