SkystarsH743HD target
iNavFlight/inav pull request #8456
Opened 2022-10-09 21:24 UTC by darsanjp

Added SkystarsH743HD target.

2022-10-10 11:37 UTC, DzikuVx requested changes
Please read https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md

As this is a new target, this PR will not be merged if all the conditions from this document are not met

2022-10-10 11:37 UTC, DzikuVx commented on src/main/target/SKYSTARSH743HD/config.c
> + * This file is part of Cleanflight.
Am, not, it's not Cleanflight, so please update the project name

2022-10-10 11:37 UTC, DzikuVx commented on src/main/target/SKYSTARSH743HD/config.c
> +   // beeperConfigMutable()->pwmMode = true;
Not needed

2022-10-10 11:37 UTC, DzikuVx commented on src/main/target/SKYSTARSH743HD/target.c
> +    //DEF_TIM(TIM4, CH4, PD15, TIM_USE_MC_MOTOR | TIM_USE_FW_SERVO, 0, 0),   // S10 DMA_NONE
Not needed, so remove

2022-10-10 22:05 UTC, darsanjp commented on src/main/target/SKYSTARSH743HD/config.c
> + * This file is part of Cleanflight.
> Am, not, it's not Cleanflight, so please update the project name

Corrected the project name .

2022-10-10 22:06 UTC, darsanjp commented on src/main/target/SKYSTARSH743HD/config.c
> +   // beeperConfigMutable()->pwmMode = true;
Removed the commented out code.

2022-10-10 22:06 UTC, darsanjp commented on src/main/target/SKYSTARSH743HD/target.c
> +    //DEF_TIM(TIM4, CH4, PD15, TIM_USE_MC_MOTOR | TIM_USE_FW_SERVO, 0, 0),   // S10 DMA_NONE
Removed the commented out code.

2022-10-10 22:35 UTC, darsanjp commented
> Please read https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md
> 
> As this is a new target, this PR will not be merged if all the conditions from this document are not met

I bought this board for a cinewoop and later found that I cant use INAV as INAV target was not available. Target for this board exists in Betaflight. I spend some time with the betaflight config file and was then able to compile an INAV target. Thanks to your video on INAV custom targets. Currently using on my quad with gps and matek lidar sensor. Working like charm. Thought of sharing it with the community. I have read the new hardware policy. Unfortunately I dont have a spare board to send to the developers. But I am willing to spend my time for development for this project.

2022-10-11 06:34 UTC, erstec commented
> > Please read https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md
> > As this is a new target, this PR will not be merged if all the conditions from this document are not met
> 
> I bought this board for a cinewoop and later found that I cant use INAV as INAV target was not available. Target for this board exists in Betaflight. I spend some time with the betaflight config file and was then able to compile an INAV target. Thanks to your video on INAV custom targets. Currently using on my quad with gps and matek lidar sensor. Working like charm. Thought of sharing it with the community. I have read the new hardware policy. Unfortunately I dont have a spare board to send to the developers. But I am willing to spend my time for development for this project.

You don't need to have spare boards and do anything about this at all. It is 100% manufacturer responsibility to do that.

2023-04-05 16:45 UTC, DzikuVx commented
Thanks @darsanjp 
Replaced by #8954

2023-04-05 16:45 UTC, closed without merging