Fix O3 overheat - clear arm flag before launch
iNavFlight/inav pull request #8727
Opened 2023-01-22 11:03 UTC by bakwc

**The problem**
 - O3 air unit getting overheat when launching with auto-launch and bungee

**Details**
 - When using auto-launch with bungee you need to spend ±40 seconds after arm and before actual through an airplane. You arm airplane, then go to the beginning of bungee cord, attach airplane to a hook, stretch a hook with the airplane and finally release an airplane. It takes a while, and the O3 air unit getting overheat.

**Proposed solution**
- Don't send an ARM flag to the air unit until launch detected

2023-01-22 11:47 UTC, Jetrell commented
Nice idea for any HD VTX.
What do you think of having it work in reverse too. By not sending the disarm flag to the VTX, until GPS speed drops below a certain value.. This may prevent the VTX from going into low power mode some distance away, causing the signal to be lost and stopping the DVR recording, if you accidentally disarm a fixed wing in flight.

2023-01-23 09:48 UTC, mmosca commented
Sounds like a good idea for most vtxs, but I think it should be optional.

It is common for video systems to prevent dvr recording before arm (due to low power mode) and users may want to have footage from the full lunch for a post morten/diagnose of launch issues (or entertainment).

2023-01-23 11:24 UTC, breadoven commented
Manipulating the MSP Arming Status flag doesn't seem the right way to go to fix this specific issue given it also affects anything else using the flag.

2023-01-23 11:54 UTC, MrD-RC commented
I agree with @breadoven. The MSP arm state should be just that. It should not be manipulated because a VTx is having a problem. A timeout for full power should be an option in the VTx/goggles firmware. Same as a delay before stopping recording.

2023-01-23 13:18 UTC, bakwc commented
Oh, thank you for the very helpful advice! May be you could be so kind and describe how it should work?
Should I create a PR to DJI O3 vtx firmware repo? May be you have a github link, I couldn't find anywhere, could you please help?
Or may be I should create a ticket to DJI support / write to DJI forum? They don't support iNav at all, they refused to add inav OSD, but they will add support for iNav autolauch mode, right?
</sarcasm>
Now serious - if you care about your users getting VTX overheated - the optional flag could be a very helpful feature. If not - feel free to close PR. Trying to make DJI fix for overheating in inav auto-launch mode is a fantastic solution from a parallel universe.

2023-01-24 08:38 UTC, DzikuVx requested changes
As I do think it's a very nice feature, implementation could be improved.
First of all, it should be optional and driven by a configuration parameter.
I'm ok with the fact that all the devices connected via MSP would get changed flag, but only if pilot made such a decision and changed a setting to enable that

2023-01-24 08:50 UTC, MrD-RC commented
I personally still don't think that MSP should be changed for one device, because they are not providing desired features to their customers. 

Think it's about it. There are many ways DJI could have done this better. For example, only boost the VTx power when they see the distance between the VTx and VRx increasing after arming. That could be a standard setting which people didn't even know about. It just worked. And in a response to the sarcastic comment which was then deleted. 

> Oh, thank you for the very helpful advice! May be you could be so kind and describe how it should work?
> Should I create a PR to DJI O3 vtx firmware repo? May be you have a github link, I couldn't find anywhere, could you please help?
> Or may be I should create a ticket to DJI support / write to DJI forum? They don't support iNav at all, they refused to add inav OSD, but they will add support for iNav autolauch mode, right?

Yes, you should raise a ticket with DJI. This has nothing to do with INAV or autolaunch. An option for a delay in boosting VTx power after arm would be useful in other firmware, not just INAV. The same way that a delay after disarm for stopping video recording would be useful. These are not flight controller firmware specific requests. DJI are the ones who should be implementing this. 

If this is implemented. It 100% should be **off** by default.

2023-01-24 09:05 UTC, bakwc commented
@MrD-RC you propose to have a fixed timer to enable VTX after a fixed amount of time and that should be configured on a VTX side. I have a few questions:
 - What will happen if user eg. set one minute timer, but, due to some circumstances launch takes longer? You never know for sure how much time will it take to make a bungee launch.
 - What will happen if user makes launch much faster? Eg. he set a launch time 1.5 minutes and he performed launched in 20 seconds this time. My ar wing pro will go for ±2 kilometers in 60 seconds, video connection will drop. Do you think it is safe?
 - And the main question - do you really think that DJI will fix this issue?

> It 100% should be off by default
Sounds reasonable

2023-01-24 09:31 UTC, breadoven commented
This would be an acceptable bodge if optional I guess. However, bodging FC firmware to fix a problem caused by the poor design of connected hardware doesn't seem the best idea especially when it involves messing with something as fundamental as Arming status.

Also, do these O3 units really overheat that quickly ? I got the impression it took several minutes. What happens when they're used on a quad that's hovering for several minutes. Do they also overheat given there's potentially no significant airflow over the case from prop wash or airspeed ?

2023-01-24 09:33 UTC, breadoven commented on src/main/fc/fc_msp.c
> +    if (!STATE(FIXED_WING_LEGACY))
`FIXED_WING_LEGACY `shouldn't be used, see runtime_config.h

2023-01-24 11:29 UTC, MrD-RC commented
> @MrD-RC you propose to have a fixed timer to enable VTX after a fixed amount of time and that should be configured on a VTX side. I have a few questions:
> 
> * What will happen if user eg. set one minute timer, but, due to some circumstances launch takes longer? You never know for sure how much time will it take to make a bungee launch.
> * What will happen if user makes launch much faster? Eg. he set a launch time 1.5 minutes and he performed launched in 20 seconds this time. My ar wing pro will go for ±2 kilometers in 60 seconds, video connection will drop. Do you think it is safe?
> * And the main question - do you really think that DJI will fix this issue?
> 

I'm not just thinking about a bungee launch, but multiple situations. To be honest, bungee launches are probably a low percentage use case anyway. And of those bungee launches, I would imagine a large percentage of those use a launch rig that doesn't require walking backwards with an armed plane to stretch out the bungee. More will have a launching ramp, which you can hook up the bungee to the plane, arm, then release the bungee.

To answer your first two points. If you actually read my suggestion for what DJI should implement. I said that DJI should detect the distance between the VTx and VRx (which it already knows). After arming, when this distance increases by a set amount, 25 metres should be fine, then go to the desired power level. That would benefit all craft, not just bungee launched planes. Everything could benefit from that.

I never mentioned a timer at all with regards to arming delay. I mentioned a timer for when disarming to have a delay before stopping the recording.

To answer the third point. I don't care. I've seen enough of how DJI treat the community to know to never send money their way. That is the only thing they listen to. Besides, it sounds like DJI have more to fix if their VTx overheats in 40 seconds, than just adding features that the community wants. My point is that unless people do pester DJI, they will never change. If people keep just bending over and taking whatever DJI gives them, with a big smile on their faces, what do you think will happen? The answer is nothing. DJI just pockets the cash and grabs a bigger dildo for next time. Bend over and remember to smile.

2023-01-24 11:49 UTC, mmosca commented
> Also, do these O3 units really overheat that quickly ? I got the impression it took several minutes. What happens when they're used on a quad that's hovering for several minutes. Do they also overheat given there's potentially no significant airflow over the case from prop wash or airspeed ?

Just for context, when testing on a bench, without a fan, it usually takes about 4-6 minutes for the o3 unit to overheat in low power mode. In a plane with poor ventilation, it may overheat quicker if you take too long to launch (and get some airflow) as it will "start" from a higher temperature point.

Arming enables higher output power modes and power hungry features on the AU (higher framerate, recording, etc) and will heat up much faster.

2023-01-24 12:56 UTC, bakwc commented
> To answer your first two points. If you actually read my suggestion for what DJI should implement. I said that DJI should detect the distance between the VTx and VRx (which it already knows). After arming, when this distance increases by a set amount, 25 metres should be fine, then go to the desired power level. That would benefit all craft, not just bungee launched planes. Everything could benefit from that.

Sorry, I missed that distance suggestion. Yeah, distance based detection on vtx side may works. Still there is an issue left that it's very unlikely to convince DJI to make this kind of test. Also, do you think that distance approach is more reliable compared to detection of auto-launch on the inav side? What about planes / quads without GPS?

> If people keep just bending over and taking whatever DJI gives them, with a big smile on their faces, what do you think will happen? The answer is nothing. DJI just pockets the cash and grabs a bigger dildo for next time. Bend over and remember to smile.

I totally agree. The problem is that they provide the best video quality on the market. So the choice is either you fly with best quality and somehow fix or ignore all other issues, or fly with on another less quality system. The only way to make them care about users is someone make a better product. Besides, there is no much alternatives. HDZero has much worse picture. Walksnail [has the same bad attitude towards community](https://github.com/fpv-wtf/wtfos/issues/45#issuecomment-1342933367), eg. they closed root access to their air unit / goggles, so wtfos is not working there.

> Also, do these O3 units really overheat that quickly ? I got the impression it took several minutes. What happens when they're used on a quad that's hovering for several minutes. Do they also overheat given there's potentially no significant airflow over the case from prop wash or airspeed ?

From quads probably it's enough airflow when hovering, for quads the airflow is not from the speed but from the rotating props. So even when you stay on the ground and arm the quad - you have some ventilation (motors starts rotating after arm). For planes in my scenario propeller is not rotating at all until you through it.

2023-01-24 14:05 UTC, bakwc commented
Made optional, disabled by default.

2023-01-24 14:05 UTC, MrD-RC commented
> > To answer your first two points. If you actually read my suggestion for what DJI should implement. I said that DJI should detect the distance between the VTx and VRx (which it already knows). After arming, when this distance increases by a set amount, 25 metres should be fine, then go to the desired power level. That would benefit all craft, not just bungee launched planes. Everything could benefit from that.
> 
> Sorry, I missed that distance suggestion. Yeah, distance based detection on vtx side may works. Still there is an issue left that it's very unlikely to convince DJI to make this kind of test. Also, do you think that distance approach is more reliable compared to detection of auto-launch on the inav side? What about planes / quads without GPS?

No problem 👍  I think it is a more universal solution. It doesn't care about the firmware or platform at all. It doesn't use the GPS. The distance is calculated based on the RF signal. This is how DJI implement the hard limit. My quad with WS shows distance from the goggles. It has no GPS.

> > If people keep just bending over and taking whatever DJI gives them, with a big smile on their faces, what do you think will happen? The answer is nothing. DJI just pockets the cash and grabs a bigger dildo for next time. Bend over and remember to smile.
> 
> I totally agree. The problem is that they provide the best video quality on the market. So the choice is either you fly with best quality and somehow fix or ignore all other issues, or fly with on another less quality system. The only way to make them care about users is someone make a better product. Besides, there is no much alternatives. HDZero has much worse picture. Walksnail [has the same bad attitude towards community](https://github.com/fpv-wtf/wtfos/issues/45#issuecomment-1342933367), eg. they closed root access to their air unit / goggles, so wtfos is not working there.

Actually, I disagree. WS are doing a great job of listening to the community. They have already implemented a lot of updates based on the requests of pilots. They are listening to what people want and working towards implementing those changes. There is now OSD recording, customisable fonts, much better image and penetration (easily as good as DJI), and the next firmware looks to have an even better image in terms of flying. More good things to come too.

There's no need for root access on WS, as they are getting everything working anyway. Why need WTFDJI when there is already full MSP DisplayPort support, with customisable fonts, and the WS developers are working with the flight controller teams. The main firmware pushing MSP DisplayPort is BetaFlight. I know for a fact that WS are working with them to make sure that the MSP DisplayPort API is followed correctly. They need it in BF 4.4 for their 4 page fonts. INAV is using the same API. The only difference is the amount of data drawn each time. But, you only need things like WTFDJI when the companies don't work with the community.
 
> > Also, do these O3 units really overheat that quickly ? I got the impression it took several minutes. What happens when they're used on a quad that's hovering for several minutes. Do they also overheat given there's potentially no significant airflow over the case from prop wash or airspeed ?
> 
> From quads probably it's enough airflow when hovering, for quads the airflow is not from the speed but from the rotating props. So even when you stay on the ground and arm the quad - you have some ventilation (motors starts rotating after arm). For planes in my scenario propeller is not rotating at all until you through it.

True enough. I guess a 1.2W AKK will heat up just as quickly. Though that only costs $20, not $200.

2023-01-24 14:18 UTC, bakwc commented
> There's no need for root access on WS

"no root access"+ "closed source code" and "community friendly" is incompatible. With wtfos devs can do a lot of custom apps. Eg. I want to make a custom OSD with minimap, I can do it with DJI and wtfos, but no chance with WS. Anyway, that's another story.

2023-01-24 14:34 UTC, MrD-RC commented
> > There's no need for root access on WS
> 
> "no root access"+ "closed source code" and "community friendly" is incompatible. With wtfos devs can do a lot of custom apps. Eg. I want to make a custom OSD with minimap, I can do it with DJI and wtfos, but no chance with WS. Anyway, that's another story.

Sorry, but that is nonsense. Open source does not have a monopoly on being community friendly. If closed source companies listen to the community and work with them, they are community friendly too. Was ArduPilot taking 5 years to implement Crossfire protocol community friendly? Sorry, but open source and community friendly are two completely different and separate things.

2023-01-24 22:32 UTC, mmosca commented on docs/Settings.md
> +Prevents VTX overheating by sending UNARMED to MSP until launch detected.
Settings.md is generated with a script.

You should update the description in the yaml to this version and regenerate the file by running src/utils/update_cli_docs.py

2023-01-28 14:31 UTC, DzikuVx requested changes
`PG_REGISTER_WITH_RESET_TEMPLATE(navConfig_t, navConfig, PG_NAV_CONFIG, 3);` has to be modified and version increased

2023-01-28 16:06 UTC, bakwc commented
> `PG_REGISTER_WITH_RESET_TEMPLATE(navConfig_t, navConfig, PG_NAV_CONFIG, 3);` has to be modified and version increased

Fixed

2023-03-06 16:31 UTC, RobinatiNav commented
I switch ON/OFF my O3 air unit using ON/OFF switch. I believe the switch can be easily controlled via telemetry on your Tx. e.g. I have my dji camera controlled via roll angle.

2023-04-07 06:34 UTC, bakwc commented
Hey! Any chance to get it merged on 6.1 or 7?

2024-03-21 10:08 UTC, closed without merging