Added Compass Calibration programmable operation
iNavFlight/inav pull request #9411
Opened 2023-10-25 17:33 UTC by sdellava

This pull request create the programmable operation n. 52

This operation trigger the Compass Calibration procedure.

This operation, activated by an AUX channel, allow the pilot to trigger the compass calibration process in air.

This option eventually solves the issue of calibrating the mag before take off, that in case of presence of large metal masses or if done close to active electronic devices, can result wrong.

2023-10-26 09:06 UTC, DzikuVx commented
@sdellava would would need a Configurator update as well

2023-10-26 09:27 UTC, sdellava commented
> @sdellava would would need a Configurator update as well

Yes, I'll submit a second PR asap

2023-10-26 09:52 UTC, sdellava commented
Momentary closed to execute additional tests.

2023-10-26 11:52 UTC, shota3527 commented
It is safe to calibrate compass in air?

2023-10-26 12:03 UTC, sdellava commented
Yes it is. I've tested it just one hour ago. But I've find an issue: the calibration process end with a "save setting" procedure that can't be executed while the ARMING_FLAG is TRUE.

The reason is that the function that save the configuration reset the rx link. Therefore it is correct that it can't be execute while armed. 

The effect of this issue is that the system message "**SAVING SETTING**" remain in the OSD until the FC is  ARMING_FLAG is turned to FALSE. Then the save setting procedure complete correctly (in the bottom of the post flight data the "SETTING SAVED" message appears. 

Anyway, on air calibration processe should not be done in a middle of a flight generic, but in a specific calibration flight, and executed only once in a place. So at the moment I'll do no other modifications related to this new feature.

2023-10-26 12:05 UTC, sdellava commented
Tested one hour ago. I've found a potential issue: the calibration process end with a "save setting" procedure that can't be executed while the ARMING_FLAG is TRUE.

The reason is that the function that save the configuration reset the rx link. Therefore it is correct that it can't be execute while armed.

The effect of this issue is that the system message "SAVING SETTING" remain in the OSD until the FC is ARMING_FLAG is turned to FALSE. Then the save setting procedure complete correctly (in the bottom of the post flight data the "SETTING SAVED" message appears.

Anyway, on air calibration processe should not be done in a middle of a flight generic, but in a specific calibration flight, and executed only once in a place. So at the moment I'll do no other modifications related to this new feature.

2023-10-26 12:57 UTC, sdellava commented
added related configurator PR https://github.com/iNavFlight/inav-configurator/pull/1854

2023-10-27 09:20 UTC, sdellava commented
Temporary closed to solve the conflict

2023-10-27 09:22 UTC, sdellava commented
Conflic solved

2023-12-16 12:54 UTC, sdellava commented
Video of the test here: https://youtu.be/1muitwEfxic

2023-12-29 13:10 UTC, sdellava commented
@DzikuVx and team... will this PR will merged or I need to change something?

2023-12-30 16:15 UTC, DzikuVx requested changes
One thing has to be fixed here, but that also means https://github.com/iNavFlight/inav-configurator/pull/1854 has to be updated

2023-12-30 16:15 UTC, DzikuVx commented on src/main/programming/logic_condition.h
> +    LOGIC_CONDITION_DISABLE_GPS_FIX             = 54,
Your entry has to have a new ID, not reuse existing one. So, `LOGIC_CONDITION_RESET_MAG_CALIBRATION` should be `54` not `53`

2023-12-30 16:38 UTC, sdellava commented
Logic condition changed to 54. configurator updated too.

2023-12-31 11:01 UTC, merged