Update displayport_msp_bf_compat.c for more remove off ? @dji goggle
iNavFlight/inav pull request #9764
Opened 2024-03-03 10:39 UTC by druckgott

Fix some more Icons for DJI Integra to do not have a ?

2024-03-03 11:26 UTC, MrD-RC requested changes

2024-03-03 11:26 UTC, MrD-RC commented on src/main/io/displayport_msp_bf_compat.c
> +        return BF_SYM_RSSI;
I think using the RSSI symbol would be confusing. Maybe use 'H' for HDP_L and 'P' for HDP_R?

2024-03-03 11:26 UTC, MrD-RC commented on src/main/io/displayport_msp_bf_compat.c
> +        return BF_SYM_RSSI;
See above comment for HDP_L

2024-03-03 11:26 UTC, MrD-RC commented on src/main/io/displayport_msp_bf_compat.c
> +        return 'd' + 'B';
You can't do this. Symbols are a single space character. Adding multiple character will cause issues with the OSD creation.

2024-03-03 11:26 UTC, MrD-RC commented on src/main/io/displayport_msp_bf_compat.c
> +        return 'd' + 'B' + 'm';
You can't do this. Symbols are a single space character. Adding multiple character will cause issues with the OSD creation.

2024-03-03 11:26 UTC, MrD-RC commented on src/main/io/displayport_msp_bf_compat.c
> +        return 'S' + 'N' + 'R';
You can't do this. Symbols are a single space character. Adding multiple character will cause issues with the OSD creation.

2024-03-03 11:26 UTC, MrD-RC commented on src/main/io/displayport_msp_bf_compat.c
> +        return 'M' + 'W';
You can't do this. Symbols are a single space character. Adding multiple character will cause issues with the OSD creation.

2024-03-03 11:26 UTC, MrD-RC commented on src/main/io/displayport_msp_bf_compat.c
> +        return 'K' + 'W';
You can't do this. Symbols are a single space character. Adding multiple character will cause issues with the OSD creation.

2024-03-03 11:45 UTC, druckgott commented
it dosend do sence currently with the points if you only have one letter.

2024-03-03 11:45 UTC, closed without merging

2024-03-05 13:31 UTC, rmaia3d commented on src/main/io/displayport_msp_bf_compat.c
> +        return 'd' + 'B';
Also, there's no support for lower case characters in the DJI font. Only upper-case.