Raise the limit to display CRSF SNR values on OSD
iNavFlight/inav pull request #9793
Opened 2024-03-12 16:07 UTC by rmaia3d

This simply raises the limit for the osd_snr_alarm setting, which controls when the SNR field (for CRSF based radio systems) is displayed on the OSD. The raised limit allows configuring the field to be constantly visible, if so desired, instead of only being visible when the SNR gets near a critical level.

Defaults are the same, so no behavior change is expected, unless the user explicitly sets the alarm threshold to a value higher than the previous limit.

2024-03-13 19:37 UTC, OptimusTi requested changes
Please change the max to 30.

2024-03-14 12:50 UTC, rmaia3d commented
> Please change the max to 30.

Done!!

2024-03-14 12:57 UTC, rmaia3d commented
> There's a reason why I used those default numbers in the code. 😉

I don't doubt it! That's why I left the defaults as they are. The whole idea was making it possible to have the SNR field permanently displayed with minimal changes to the code.
 
> Also, the filtering should be removed.

Ok, I will do this as well.

2024-05-10 07:07 UTC, DzikuVx requested changes
@rmaia3d This PR has the code that is not related to the change. No idea from where it got here but please resolve issues so only feature related code is included. Thanks

2024-05-12 03:26 UTC, rmaia3d commented
> @rmaia3d This PR has the code that is not related to the change. No idea from where it got here but please resolve issues so only feature related code is included. Thanks

No problem! That extra code probably sneaked itself in when the base branch was changed. I rebased my PR branch on master and it seems to have resolved. Please let me know if anything else is needed on my part.

2025-11-12 21:34 UTC, merged